


-- THÊM CỘT BẢNG ITEM, SẢN PHẨM
ALTER TABLE base.ITEM 
ADD [GROUP_ITEM] INT,[WOOD_TYPE_ID]  INT

-- THÊM CỘT MODULEID CHO BẢNG DEPARTMENT
ALTER TABLE base.DEPARTMENT
ADD [MODULE_ID] INT
--CẬP NHẬT CHO TẤT CẢ VỀ MODULE SẢN XUẤT
UPDATE base.DEPARTMENT SET MODULE_ID=100001
-- THÊM CỘT BẢNG NHÀ CUNG CẤP
ALTER TABLE base.VENDOR
ADD [ADDRESS] NVARCHAR(500),[MODULE_ID] INT,[STAFF_ID] INT,[IS_INVOICE] BIT,[IS_COC] BIT,[REGION_ID] INT,[REGION_SHIPPING_ID] INT


-- TẠO BẢNG VÙNG 
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME='REGION')
	CREATE TABLE wood.REGION(
		[ID] INT IDENTITY(100000,1) PRIMARY KEY,
		[GUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
		[CODE] VARCHAR(30) NOT NULL,
		[NAME] NVARCHAR(100) NOT NULL,
		[DESCRIPTIONS] NVARCHAR(400) NULL,
		[MODULE_ID] INT
	)
GO
--  TẠO BẢNG VÙNG VẬN CHUYỂN
IF NOT EXISTS( SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME ='REGION_SHIPPING')
	CREATE TABLE wood.REGION_SHIPPING(
		[ID] INT IDENTITY(100000,1) PRIMARY KEY,
		[GUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
		[CODE] VARCHAR(30) NOT NULL,
		[NAME] NVARCHAR(100) NOT NULL,
		[DESCRIPTIONS] NVARCHAR(400) NULL,
		[MODULE_ID] INT
	)
GO
-- TẠO BẢNG BẢNG GIÁ
IF NOT EXISTS( SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME ='WOOD_PRICE_LIST')
	CREATE TABLE wood.WOOD_PRICE_LIST(
		[ID] INT IDENTITY(100000,1) PRIMARY KEY,
		[GUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
		[PRICE] NVARCHAR(100) NOT NULL,
		[ITEM_PRICE_CODE] NVARCHAR(400) NULL,
		[REQ_ID] INT NOT NULL,
		[REGION_ID] INT NOT NULL,
		[CREATE_BY] INT NOT NULL,
		[CREATE_AT] DATETIME NOT NULL,
		[APPLY_STATUS] INT NOT NULL,
		[APPLY_DATE] DATETIME,
		[APPLY_BY] INT
	)
GO
-- TẠO BẢNG  PHIẾU NHẬP KHO
IF NOT EXISTS( SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME ='WH_RECEIPT')
	CREATE TABLE wood.WH_RECEIPT(
		[ID] INT IDENTITY(100000,1) PRIMARY KEY,
		[GUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
		[NUMBER_OF_MONTH] INT NOT NULL,
		[MONTH] INT NOT NULL,
		[YEAR] INT NOT NULL,
		[WAREHOUSE_ID] INT NOT NULL,-- LIKN  BASE.DEPARTMENT
		[VENDOR_ID] INT NOT NULL,
		[QC_STAFF] INT NULL,
		[CAR_LICENSE_PLATE] VARCHAR(50) NULL,
		[ALLOW_INSPECTION] BIT,
		[ALLOW_PAY] BIT,
		[MODULE_ID] INT,
		[RECEIPT_DATE] DATETIME,
		[CREATE_AT] DATETIME,
		[FORKLIFT] BIT,
		[CREATE_BY] INT,
		[DEL_FLAG] NCHAR(10)
	)
GO
-- TẠO BẢNG KIỂU NHẬP 
IF NOT EXISTS( SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME ='WH_INPUT_TYPE')
	CREATE TABLE wood.WH_INPUT_TYPE(
		[ID] INT IDENTITY(100000,1) PRIMARY KEY,
		[GUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
		[CODE] VARCHAR(30),
		[ITYPE] VARCHAR(20),
		[NAME] NVARCHAR(140),
		[MODULE_ID] INT
	)
GO
-- TẠO BẢNG PHIẾU NHẬP KHO CHI TIẾT
IF NOT EXISTS( SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME ='WH_RECEIPT_DTL')
	CREATE TABLE wood.WH_RECEIPT_DTL(
		[ID] INT IDENTITY(100000,1) PRIMARY KEY,
		[GUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
		[WH_RECEIPT_ID] INT NOT NULL,
		[ITEM_ID] INT NOT NULL,
		[PCS_PER_PACKAGE] INT,-- SỐ THANH TRÊN BÓ
		[PACKAGE_QUANTITY] INT , -- SỐ BÓ
		[INPUT_TYPE_ID] INT,
		[NOTE] NVARCHAR(300),
		[RETURN_ID] INT, -- PHIEU TRA VE
		[LEAVE] NCHAR(10),
		[OVER_PLAN] BIT,
		[SAMPLE_PACKAGE_QUANTITY] INT,-- DÙNG CHO GỖ KEO XẺ
		[SAMPLE_QUANTITY] INT,-- DÙNG CHO VÁN
		[DEL_FLAG] NCHAR(10)
	)
GO
ALTER TABLE wood.WH_RECEIPT_DTL
ADD CREATE_AT DATETIME,CREATE_BY INT,MODIFY_AT DATETIME,MODIFY_BY INT

-- TẠO BẢNG NGHIỆM THU
IF NOT EXISTS( SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME ='WOOD_INSPECTION')
	CREATE TABLE wood.WOOD_INSPECTOR(
		[ID] INT IDENTITY(100000,1) PRIMARY KEY,
		[GUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
		[INPUT_TYPE_ID] INT,
		[RECEIPT_ID] INT,
		[ITEM_ID] INT,
		[NOTE] NVARCHAR(200),
		[SIZE_OUT_RATE] FLOAT,
		[HUMIDITY] FLOAT,-- ĐỘ ẨM (30%)
		[IS_DOUBLE] NCHAR(10),-- DÙNG CHO GỖ KEO XẺ
		[DEL_FLAG] NCHAR(10),
		[CREATE_AT] DATETIME,
		[CREATE_BY] INT,
		[UPDATE_AT] DATETIME,
		[UPDATE_BY] INT
	)
GO
-- TẠO BẢNG BB TÍNH TIỀN
IF NOT EXISTS( SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME ='WOOD_PAY_CALCULATOR')
	CREATE TABLE wood.WOOD_PAY_CALCULATOR(
		[ID] INT IDENTITY(100000,1) PRIMARY KEY,
		[GUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
		[INPUT_TYPE_ID] INT,
		[RECEIPT_ID] INT,
		[ITEM_ID] INT,
		[NOTE] NVARCHAR(200),
		[SIZE_OUT_RATE] FLOAT,
		[HUMIDITY] FLOAT,-- ĐỘ ẨM (30%)
		[IS_DOUBLE] NCHAR(10),-- DÙNG CHO GỖ KEO XẺ
		[DEL_FLAG] NCHAR(10),
		[COMPANY_PRICE] INT,
		[ITYPE_PRICE] INT,
		[AVERAGE_PRICE] INT,
		[CREATE_AT] DATETIME,
		[CREATE_BY] INT,
		[UPDATE_AT] DATETIME,
		[UPDATE_BY] INT
	)
GO
-- BẢNG LƯU THÔNG TIN TÍNH TIỀN
IF NOT EXISTS( SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME ='WOOD_PAY_SAVE')
	CREATE TABLE wood.WOOD_PAY_SAVE(
		[ID] INT IDENTITY(100000,1) PRIMARY KEY,
		[GUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
		[RECEIPT_ID] INT,
		[IS_INVOICE] BIT,
		[IS_COC] BIT,
		[SHIPPING_FEE] INT,
		[OTHER_SUPPORT_FEE] INT,
		[TOTAL_PAY] INT,
		[AVERAGE_PRICE] INT,
		[WH_VOLUMN] FLOAT,
		[QC_VOLUMN] FLOAT,
		[INPUT_RATE] FLOAT,
		[PAY_RATE] FLOAT,
		[TOTAL_NOT_TAX] INT,
		[APPROVAL_STATUS] INT,
		[CREATE_AT] DATETIME,
		[CREATE_BY] INT,
	)
GO