INSERT INTO base.VENDOR ([GUID],[CODE],[NAME],[ACTIVE],[CREATE_BY],[CREATE_DATE],[ADDRESS],[MODULE_ID])
VALUES(NEWID(),'GO228',N'Công ty cổ phần Woodsland Tuyên Quang',1,100031,GETDATE(),N'Tuyên Quang',100006)

INSERT INTO base.VENDOR ([GUID],[CODE],[NAME],[ACTIVE],[CREATE_BY],[CREATE_DATE],[ADDRESS],[MODULE_ID])
VALUES(NEWID(),'GO301',N'Công ty TNHH Sao Việt Tuyên Quang',1,100031,GETDATE(),N'Tuyên Quang',100006)

INSERT INTO base.VENDOR ([GUID],[CODE],[NAME],[ACTIVE],[CREATE_BY],[CREATE_DATE],[ADDRESS],[MODULE_ID])
VALUES(NEWID(),'GO320',N'Công ty TNHH MTV vận tải và thương mại Ngọc Khánh',1,100031,GETDATE(),N'Tuyên Quang',100006)

INSERT INTO base.VENDOR ([GUID],[CODE],[NAME],[ACTIVE],[CREATE_BY],[CREATE_DATE],[ADDRESS],[MODULE_ID])
VALUES(NEWID(),'GO314',N'Công ty TNHH TM An Phát Việt Nam',1,100031,GETDATE(),N'Tuyên Quang',100006)

INSERT INTO base.VENDOR ([GUID],[CODE],[NAME],[ACTIVE],[CREATE_BY],[CREATE_DATE],[ADDRESS],[MODULE_ID])
VALUES(NEWID(),'GOKH225',N'Công ty TNHH Plywood Hưng Phát',1,100031,GETDATE(),N'Tuyên Quang',100006)

INSERT INTO base.VENDOR ([GUID],[CODE],[NAME],[ACTIVE],[CREATE_BY],[CREATE_DATE],[ADDRESS],[MODULE_ID])
VALUES(NEWID(),'HCKH079',N'CÔNG TY TNHH POWERPLY (VIET NAM)',1,100031,GETDATE(),N'Tuyên Quang',100006)

INSERT INTO base.VENDOR ([GUID],[CODE],[NAME],[ACTIVE],[CREATE_BY],[CREATE_DATE],[ADDRESS],[MODULE_ID])
VALUES(NEWID(),'GO310',N'Hợp tác xã Ngọc Khánh',1,100031,GETDATE(),N'Tuyên Quang',100006)

INSERT INTO base.VENDOR ([GUID],[CODE],[NAME],[ACTIVE],[CREATE_BY],[CREATE_DATE],[ADDRESS],[MODULE_ID])
VALUES(NEWID(),'GOKH226',N'Công ty TNHH Chế Biến Lâm sản Mai Nam',1,100031,GETDATE(),N'Tuyên Quang',100006)