-- KHỞI TẠO DỮ LIỆU BẢNG KIỂU NHẬP KHO, VÀ HẠ CẤP
INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('HLA',N'Hàng Loại A','INPUT',100006)
INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('HLB',N'Hàng Loại B','INSPECTION',100006)

INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('CP',N'Chính Phẩm','INPUT',100000)
INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('HC',N'Hạ Cấp','INPUT',100000)
INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('NHLB',N'Hàng Loại B','INPUT',100000)
INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('NHLC',N'Hàng Loại C','INPUT',100000)
INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('NHL',N'Hàng Loại','INPUT',100000)

INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('HC1',N'Hạ Cấp 1','INSPECTION',100000)
INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('HC2',N'Hạ Cấp 2','INSPECTION',100000)
INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('HC3',N'Hạ Cấp 3','INSPECTION',100000)
INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('HC4',N'Hạ Cấp 4','INSPECTION',100000)
INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('HC5',N'Hạ Cấp 5','INSPECTION',100000)
INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('HLB',N'Hàng Loại B','INSPECTION',100000)
INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('HLC',N'Hàng Loại C','INSPECTION',100000)
INSERT INTO wood.WH_INPUT_TYPE([CODE],[NAME],[ITYPE],[MODULE_ID]) VALUES('HL',N'Hàng Loại','INSPECTION',100000)

---  THÊM DỮ LIỆU BẢNG VÙNG VẬN CHUYỂN
INSERT INTO wood.REGION_SHIPPING([CODE],[NAME],[DESCRIPTIONS],[MODULE_ID]) VALUES('NOR',N'Chung',N'Vùng chung',100000)
INSERT INTO wood.REGION_SHIPPING([CODE],[NAME],[DESCRIPTIONS],[MODULE_ID]) VALUES('QT',N'Chung',N'Vùng Quảng Trị',100000)
INSERT INTO wood.REGION_SHIPPING([CODE],[NAME],[DESCRIPTIONS],[MODULE_ID]) VALUES('TH',N'Chung',N'Vùng Thanh Hóa',100000)
INSERT INTO wood.REGION_SHIPPING([CODE],[NAME],[DESCRIPTIONS],[MODULE_ID]) VALUES('NA',N'Chung',N'Vùng Nghệ An',100000)
INSERT INTO wood.REGION_SHIPPING([CODE],[NAME],[DESCRIPTIONS],[MODULE_ID]) VALUES('HT',N'Chung',N'Vùng Hà Tĩnh',100000)
-- THÊM VÙNG 
INSERT INTO wood.REGION([CODE],[NAME],[DESCRIPTIONS],[MODULE_ID]) VALUES('NOR',N'Chung',N'Vùng CHUNG',100000)
INSERT INTO wood.REGION([CODE],[NAME],[DESCRIPTIONS],[MODULE_ID]) VALUES('QT',N'QUẢNG TRỊ',N'Vùng QUẢNG TRỊ',100000)

-- THÊM 1 SỐ NHÀ CUNG CẤP CHO MẢNG VÁN 
INSERT INTO base.VENDOR([GUID],[CODE],[NAME],[ACTIVE],[CREATE_BY],[CREATE_DATE],[ADDRESS],
[MODULE_ID],[IS_INVOICE])
VALUES(NEWID(),'SVTQ',N'Công ty TNHH Sao Việt Tuyên Quang',1,100031,GETDATE(),N'Hàm Yên - Tuyên Quang',100006,1)

-- THÊM KHO 
INSERT INTO base.DEPARTMENT([GUID],[TYPE],[PARENT_ID],[CODE],[NAME],[TYPE2],[MODULE_ID])
VALUES(NEWID(),'KHO',100007,'VAN.YS',N'Kho Gỗ dán Yên Sơn','stock',100006)
---100083


select * from base.MODULE
select * from base.ACCOUNT where ACCOUNT='ADMIN'
SELECT * FROM base.VENDOR WHERE MODULE_ID=100006

SELECT * FROM BASE.DEPARTMENT WHERE MODULE_ID=100006

