CREATE OR ALTER PROC wood.Proc_Create_Wood_Inspection @RECEIPT_ID INT,@ITEM_ID INT,@NOTE NVARCHAR(300),
	@SIZE_OUT_RATE FLOAT,@HUMIDITY FLOAT,@ISDOUBLE NCHAR(10),@INPUT_TYPE_ID INT,@UID INT
AS
BEGIN
	INSERT INTO wood.WOOD_INSPECTOR([RECEIPT_ID],[INPUT_TYPE_ID],[ITEM_ID],[NOTE],[SIZE_OUT_RATE],[HUMIDITY],[IS_DOUBLE],[DEL_FLAG],[CREATE_AT],[CREATE_BY])
	VALUES(@RECEIPT_ID,@INPUT_TYPE_ID,@ITEM_ID,@NOTE,@SIZE_OUT_RATE,@HUMIDITY,@ISDOUBLE,'N',GETDATE(),@UID)
	SELECT 1 AS [RESULT], N'Thành công !' AS [MESSAGE]
END
