IF OBJECT_ID ( 'Proc_Create_WareHouse_Receipt', 'P' ) IS NOT NULL  
    DROP PROCEDURE wood.[Proc_Create_WareHouse_Receipt];  
GO  

CREATE OR ALTER PROC wood.[Proc_Create_WareHouse_Receipt]
	@WAREHOUSE_ID  INT, @RECEIPT_DATE DATETIME,@CAR_LICENSE_PLATE VARCHAR(50), @VENDOR_ID INT,
	@FORLIFT  BIT,@UID INT,@MODULEID INT
AS
BEGIN
	DECLARE @YEAR AS INT,@MONTH  AS INT,@MAX_NUMBER_OF_MONTH AS INT,@RESULT AS BIT,@MESSAGE AS NVARCHAR(300)
	SELECT @MONTH = DATEPART(MONTH,@RECEIPT_DATE),@YEAR = DATEPART(YEAR,@RECEIPT_DATE)
	SELECT @MAX_NUMBER_OF_MONTH = MAX(NUMBER_OF_MONTH) FROM wood.WH_RECEIPT WHERE [WAREHOUSE_ID]=@WAREHOUSE_ID AND [MONTH] =@MONTH AND [YEAR] = @YEAR AND DEL_FLAG='N'
	IF @MAX_NUMBER_OF_MONTH IS NULL
		SELECT @MAX_NUMBER_OF_MONTH = 0
	BEGIN TRY
		INSERT INTO wood.WH_RECEIPT(NUMBER_OF_MONTH,[MONTH],[YEAR],[WAREHOUSE_ID],[VENDOR_ID],[CAR_LICENSE_PLATE],[ALLOW_INSPECTION],
		[ALLOW_PAY],[FORKLIFT],[RECEIPT_DATE],[CREATE_AT],[CREATE_BY],[DEL_FLAG],[MODULE_ID])
		VALUES(@MAX_NUMBER_OF_MONTH+1,@MONTH,@YEAR,@WAREHOUSE_ID,@VENDOR_ID,@CAR_LICENSE_PLATE,1,0,@FORLIFT,@RECEIPT_DATE,GETDATE(),@UID,'N',@MODULEID)
		SELECT @RESULT =1, @MESSAGE=N' Thêm mới thành công !'
	END TRY
	BEGIN CATCH
		SELECT @RESULT=0,@MESSAGE =ERROR_MESSAGE()
	END CATCH

	SELECT @RESULT AS [RESULT],@MESSAGE AS  [MESSAGE]
END
