CREATE OR ALTER PROC wood.Proc_Create_Detail_WH_Receipt
	@RECEIPT_ID INT,@ITEM_ID INT,@PCS_PACKAGE INT,@PACKAGE_QUANTITY INT,
	@INPUT_TYPE_ID INT,@NOTE NVARCHAR(300),@LEAVE  BIT,@OVERPLAN BIT,@UID INT
AS
BEGIN
	INSERT INTO wood.WH_RECEIPT_DTL([WH_RECEIPT_ID],[ITEM_ID],[PCS_PER_PACKAGE],[PACKAGE_QUANTITY],[INPUT_TYPE_ID],
	[NOTE],[LEAVE],[OVER_PLAN],[DEL_FLAG],CREATE_AT,CREATE_BY)
	VALUES(@RECEIPT_ID,@ITEM_ID,@PCS_PACKAGE,@PACKAGE_QUANTITY,@INPUT_TYPE_ID,@NOTE,@LEAVE,@OVERPLAN,'N',GETDATE(),@UID)
	SELECT 1 AS [RESULT],N'Thành công !' AS [MESSAGE],@LEAVE AS LEAVE
END




SELECT * FROM WOOD.WH_RECEIPT_DTL

SELECT * FROM wood.[WH_RECEIPT_DTL]  WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N' AND LEAVE=0


SELECT * FROM WOOD.WH_RECEIPT

