CREATE OR ALTER PROC wood.Proc_Reload_Payment 
@RECEIPT_ID INT
AS
BEGIN
	DECLARE 
		@CID AS INT, -- ID CỦA MÃ NHẬP KHO , HOẶC ID CỦA HẠ CẤP
		@INPUT_TYPE_ID AS INT, -- ID HẠ CẤP
		@COMPANY_PRICE AS INT, -- ĐƠN GIÁ CÔNG TY,
		@PRICE_OF_TYPE AS INT, -- ĐƠN GIÁ THEO LOẠI
		@NOTE AS NVARCHAR(300), -- GHI CHÚ
		@ITEM_ID AS INT, -- ID CỦA SẢN PHẨM, ITEM
		@DTYPE NCHAR(10), -- LOẠI CỦA SẢN PHẨM , KHÔ, ƯỚT , LOẠI 1 , LOẠI 2
		@QUANTITY AS INT, -- TỔNG SỐ LƯỢNG NHẬP
		@VOLUMN_OF_ITEM AS FLOAT, -- KHỐI LƯỢNG CỦA 1 ITEM
		@WH_VOLUMN AS FLOAT, -- KHỐI LƯỢNG NHẬP KHO
		@RECEIPT_DATE AS DATETIME , -- NGÀY NHẬP KHO CỦA BIÊN BẢN
		@VENDOR_REGION_ID AS INT, -- VÙNG CỦA NHÀ CUNG CẤP
		@UID AS INT,  -- TÀI KHOẢN
		@MAX_ID_DLT AS INT,-- ID LỚN NHẤT
		@LOOP_ID_DLT AS INT,-- BIẾN VÒNG LẶP DLT
		@INSPECT_RATE AS FLOAT, -- SỐ LƯỢNG LỖI
		@PAY_RATE AS FLOAT, -- TỶ  LỆ THANH TOÁN
		@QC_VOLUMN AS FLOAT, -- TỶ LỆ QC
		@TOTAL_DEFECT_QTY AS INT,  -- TỔNG SỐ LƯỢNG LỖI CỦA 1 MÃ NHẬP KHO
		@GOOD_QTY AS INT, -- SỐ LƯỢNG ĐẠT YÊU CẦU HẠ CẤP , ĐƯỢC NHẬP TRONG BIÊN BẢN TÍNH TIỀN
		@RESULT AS BIT, -- KẾT QUẢ CỦA PROCEDUCE
		@MESSAGE AS NVARCHAR(300),
		@SAMPLE_QTY INT -- 
		-- LẤY NGÀY NHẬP KHO, VÙNG CỦA NHÀ CUNG CẤP
		SELECT @RECEIPT_DATE = RECEIPT_DATE,@VENDOR_REGION_ID= VD.[REGION_ID]
		FROM wood.WH_RECEIPT AS WH
		INNER JOIN base.VENDOR AS VD ON VD.[ID] = WH.[VENDOR_ID]
		WHERE WH.ID = @RECEIPT_ID

		-- LẤY MAX ID DLT
		SELECT @LOOP_ID_DLT = MIN(ID),@MAX_ID_DLT=MAX(ID) FROM wood.[WH_RECEIPT_DTL] WHERE WH_RECEIPT_ID=@RECEIPT_ID

		WHILE (@LOOP_ID_DLT IS NOT NULL AND @LOOP_ID_DLT<=@MAX_ID_DLT)
		BEGIN
			SELECT @CID = DLT.[ID],@INPUT_TYPE_ID = DLT.[INPUT_TYPE_ID],
			@WH_VOLUMN = DLT.PCS_PER_PACKAGE* DLT.[PACKAGE_QUANTITY]*IT.[VOLUMN],
			@QUANTITY  = DLT.PCS_PER_PACKAGE* DLT.[PACKAGE_QUANTITY],
			@DTYPE = DLT.[DTYPE],@SAMPLE_QTY = SAMPLE_QUANTITY
			FROM WH_RECEIPT_DTL AS DLT
			INNER JOIN base.ITEM AS IT ON IT.[ID] = DLT.[ID]
			WHERE DLT.[ID] = @LOOP_ID_DLT
			-- LẤY GIÁ
			SELECT @COMPANY_PRICE = dbo.FUNC_GET_PRICE_WOOD(@RECEIPT_DATE,@ITEM_ID,@DTYPE,@VENDOR_REGION_ID);
			-- LẤY TỶ LỆ NGHIỆM THU
			SELECT @INSPECT_RATE = ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
			WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=@RECEIPT_ID AND DEL_FLAG='N')
			AND DEL_FLAG='N')  AS FLOAT)/CAST(SAMPLE_QUANTITY AS FLOAT),4) 
			FROM wood.WH_RECEIPT_DTL
			WHERE WH_RECEIPT_ID=@RECEIPT_ID AND DEL_FLAG='N'
			-- TỶ LỆ THANH TOÁN
			SET @PAY_RATE = 100 -(@INSPECT_RATE*100)
			-- TÍNH THỂ TÍCH QC
			-- QC_VOLUMN = KHỐI LƯỢNG KHO * TỶ LỆ NGHIỆM THU
			SET @QC_VOLUMN = @WH_VOLUMN*@INSPECT_RATE
			-- LẤY TỔNG SỐ LƯỢNG LỖI


			SELECT @TOTAL_DEFECT_QTY = SUM(DEFECT_QTY) FROM wood.WOOD_INSPECTION 
			WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=@RECEIPT_ID AND DEL_FLAG='N')

			SELECT @GOOD_QTY = SAMPLE_QUANTITY - @TOTAL_DEFECT_QTY FROM wood.WH_RECEIPT_DTL WHERE ID = @LOOP_ID_DLT
			-- INSERT ->>>>>>
			INSERT INTO wood.WOOD_PAY_CALCULATOR
			([INPUT_TYPE_ID],[ITEM_ID],[NOTE],[COMPANY_PRICE],[ITYPE_PRICE],[QC_VOLUMN],[WH_VOLUMN],[GOOD_QTY],[RECEIPT_QTY],[CID])
			VALUES(@INPUT_TYPE_ID,@ITEM_ID,@NOTE,@COMPANY_PRICE,@PRICE_OF_TYPE,@QC_VOLUMN,@WH_VOLUMN,@GOOD_QTY,@QUANTITY,@CID)

			-- LOOP INSPECTION
			DECLARE @LOOP_INSPECT_ID AS INT,@MAX_INSPECT_ID AS INT
			SELECT @LOOP_INSPECT_ID = MIN(ID),@MAX_INSPECT_ID = MAX(ID) FROM wood.WOOD_INSPECTION WHERE RECEIPT_ID=@LOOP_ID_DLT
			
			WHILE (@LOOP_INSPECT_ID IS NOT NULL AND @LOOP_INSPECT_ID<=@MAX_INSPECT_ID)
			BEGIN
				DECLARE @INS_INPUT_TYPE_ID AS INT,@INS_ITEM_ID AS INT,@INS_DTYPE AS INT,@INS_COM_PRICE AS INT,
						@INS_TYP_PRICE AS INT,@INS_INS_RATE AS FLOAT,@INS_PAY_RATE AS FLOAT,@INS_CID AS INT,
						@INS_QC_VOLUMN AS FLOAT,@INS_IT_VOLUMN AS FLOAT,@INS_GOOD_QTY AS INT,@INS_HUMIDITY AS FLOAT,
						@INS_NOTE AS NVARCHAR(300)

				SELECT @INS_ITEM_ID  =  ITEM_ID,@INS_INPUT_TYPE_ID = INPUT_TYPE_ID,@INS_GOOD_QTY = DEFECT_QTY,
				@INS_CID = INS.ID,@INS_IT_VOLUMN = IT.VOLUMN*@QUANTITY,@INS_HUMIDITY = HUMIDITY,@INS_NOTE=NOTE
				FROM wood.WOOD_INSPECTION AS INS
				INNER JOIN base.ITEM AS IT ON IT.ID = INS.ITEM_ID
				WHERE INS.ID = @LOOP_ID_DLT

				SET @INS_INS_RATE = 1 - @INSPECT_RATE
				-- KHỐI LƯỢNG QC VÀ TỶ LỆ THANH TOÁN CHO HẠ CẤP
				SELECT @INS_QC_VOLUMN = @INS_INS_RATE * @INS_IT_VOLUMN
				-- LẤY GIÁ QUI CÁCH HẠ CẤP

				--NẾU ĐỘ ẨM CỦA HẠ CẤP NHỎ HƠN 30 % THỲ LÀ HÀNG ƯỚT
				IF @INS_HUMIDITY<=30
					SET @INS_DTYPE ='U'
				ELSE 
					SET @INS_DTYPE='K'

				-- TÍNH TỶ LỆ THANH TOÁN CHO HẠ CẤP
				-- INS_PAY_RATE = 100 - PAY_RATE
				SET @INS_PAY_RATE = 1 -@PAY_RATE
				

				SELECT @INS_COM_PRICE = dbo.FUNC_GET_PRICE_WOOD(@RECEIPT_DATE,@INS_ITEM_ID,@INS_DTYPE,@VENDOR_REGION_ID)

				INSERT INTO wood.WOOD_PAY_CALCULATOR([INPUT_TYPE_ID],[RECEIPT_ID],[ITEM_ID],[NOTE],[COMPANY_PRICE],[ITYPE_PRICE],[CID],[PAY_RATE],[QC_VOLUMN],[GOOD_QTY],
				[RECEIPT_QTY],[CID]) VALUES(
				@INS_INPUT_TYPE_ID,@RECEIPT_ID,@ITEM_ID,@INS_NOTE,@INS_COM_PRICE,@INS_COM_PRICE,@CID,@INS_PAY_RATE
				)
			END
			-- INCREMENT LOOP COUNTER
			SELECT @LOOP_INSPECT_ID = MIN(ID) FROM wood.WH_RECEIPT_DTL WHERE ID>@LOOP_ID_DLT AND WH_RECEIPT_ID=@RECEIPT_ID
		END
		SELECT @RESULT AS [RESULT],@MESSAGE AS [MESSAGE]
END



SELECT MIN(ID) FROM wood.WH_RECEIPT_DTL WHERE  WH_RECEIPT_ID=100000

SELECT id FROM wood.WH_RECEIPT_DTL WHERE  WH_RECEIPT_ID=100000 AND ID > 100000


SELECT  DLT.[ID],DLT.[ITEM_ID],DLT.[PCS_PER_PACKAGE]*DLT.[PACKAGE_QUANTITY] AS [QUANTITY],
DLT.[INPUT_TYPE_ID],DLT.NOTE,DLT.[SAMPLE_PACKAGE_QUANTITY],DLT.[SAMPLE_QUANTITY],DLT.[DTYPE],
DLT.[WH_RECEIPT_ID],IT.[NAME],IT.[CODE],RC.VENDOR_ID,VD.[REGION_ID],PRC.PRICE,'INPUT' AS [XTYPE],
DLT.[PCS_PER_PACKAGE]*DLT.[PACKAGE_QUANTITY]*IT.[VOLUMN] AS [WH_COLUMN]
FROM wood.WH_RECEIPT_DTL AS DLT
INNER JOIN base.ITEM AS IT ON IT.[ID] = DLT.[ITEM_ID]
INNER JOIN wood.WH_RECEIPT AS RC ON RC.ID = DLT.[WH_RECEIPT_ID]
INNER JOIN base.VENDOR AS VD ON VD.[ID] = RC.[VENDOR_ID]
INNER JOIN wood.WOOD_PRICE_LIST AS PRC ON  PRC.ITEM_ID= IT.ID AND PRC.APPLY_STATUS=1 AND PRC.REGION_ID=VD.REGION_ID
WHERE WH_RECEIPT_ID=100000
UNION ALL

--SELECT * 
--FROM wood.WOOD_INSPECTION  AS INS
--INNER JOIN base.ITEM AS IT ON IT.[ID] = INS.[ITEM_ID]
--INNER JOIN wood.WH_RECEIPT_DTL AS DLT ON DLT.[ID] = INS.[RECEIPT_ID]
--INNER JOIN  



SELECT * FROM wood.WOOD_INSPECTION

SELECT * FROM wood.WH_RECEIPT_DTL

SELECT * FROM wood.WOOD_PAY_CALCULATOR

SELECT *
FROM wood.WH_RECEIPT_DTL AS DLT 
INNER JOIN wood.WOOD_INSPECTION AS INS ON INS.RECEIPT_ID=DLT.ID

SELECT ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
AND DEL_FLAG='N')  AS FLOAT)/CAST(SAMPLE_QUANTITY AS FLOAT),4) 
FROM wood.WH_RECEIPT_DTL
WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N'

SELECT * FROM wood.WH_RECEIPT_DTL

SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
AND DEL_FLAG='N'

SELECT CAST( 38 AS FLOAT)/CAST(74 AS FLOAT)


