SELECT  DLT.ID AS [CID],DLT.INPUT_TYPE_ID  ,DLT.ITEM_ID,DLT.DTYPE,DLT.PCS_PER_PACKAGE,
DLT.PACKAGE_QUANTITY,DLT.PCS_PER_PACKAGE*DLT.PACKAGE_QUANTITY AS [TOTAL_QTY],
DLT.SAMPLE_PACKAGE_QUANTITY,DLT.SAMPLE_QUANTITY,
(100 - ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
		WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
		AND DEL_FLAG='N')  AS FLOAT)/CAST(SAMPLE_QUANTITY AS FLOAT),4)*100) AS [INS_RATE],
CASE	
	WHEN (100 - ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
		WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
		AND DEL_FLAG='N')  AS FLOAT)/CAST(SAMPLE_QUANTITY AS FLOAT),4)*100) >=90
	THEN 
		100
	WHEN (100 - ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
		WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
		AND DEL_FLAG='N')  AS FLOAT)/CAST(SAMPLE_QUANTITY AS FLOAT),4)*100) >=80	AND
		(100 - ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
		WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
		AND DEL_FLAG='N')  AS FLOAT)/CAST(SAMPLE_QUANTITY AS FLOAT),4)*100) < 90
	THEN
		(100 - ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
		WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
		AND DEL_FLAG='N')  AS FLOAT)/CAST(SAMPLE_QUANTITY AS FLOAT),4)*100) + 5
	ELSE
		(100 - ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
		WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
		AND DEL_FLAG='N')  AS FLOAT)/CAST(SAMPLE_QUANTITY AS FLOAT),4)*100)
	END AS [PAY_RATE],
	IT.VOLUMN AS [ITEM_VOLUMN],
	(100 - ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
		WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
		AND DEL_FLAG='N')  AS FLOAT)/CAST(SAMPLE_QUANTITY AS FLOAT),4)*100)*IT.VOLUMN*DLT.PCS_PER_PACKAGE*DLT.PACKAGE_QUANTITY/100 AS [QC_VOLUMN],
	IT.VOLUMN*DLT.PCS_PER_PACKAGE*DLT.PACKAGE_QUANTITY AS [WH_VOLUMN],
	dbo.FUNC_GET_PRICE_WOOD((SELECT RECEIPT_DATE FROM wood.WH_RECEIPT WHERE ID = 100000),DLT.ITEM_ID,DLT.DTYPE,
	(SELECT REGION_ID FROM base.VENDOR WHERE ID = (SELECT VENDOR_ID FROM wood.WH_RECEIPT WHERE ID = 100000))) AS [COM_PRICE]
FROM wood.WH_RECEIPT_DTL AS DLT
INNER JOIN base.ITEM AS IT ON IT.ID = DLT.ITEM_ID
WHERE DLT.[WH_RECEIPT_ID] =100000

UNION ALL

SELECT INS.ID AS [CID],INPUT_TYPE_ID,ITEM_ID,CASE WHEN HUMIDITY <=30 THEN 'U'  ELSE 'K' END AS [DTYPE],
0 AS [PCS_PER_PACKAGE],0 AS [PACKAGE_QUANTITY],0 AS [TOTAL_QTY],0 AS [SAMPLE_PACKAGE_QUANTITY],
0 AS [SAMPLE_QUANTITY],ROUND(CAST(DEFECT_QTY AS FLOAT)/CAST((SELECT SAMPLE_QUANTITY FROM wood.WH_RECEIPT_DTL WHERE ID=RECEIPT_ID)AS FLOAT),4)*100 AS [INS_RATE],
CASE
	WHEN (100 - ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
		WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
		AND DEL_FLAG='N')  AS FLOAT)/CAST((SELECT SAMPLE_QUANTITY FROM wood.WH_RECEIPT_DTL WHERE ID=RECEIPT_ID) AS FLOAT),4)*100) >= 90
	THEN 100
	WHEN (100 - ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
		WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
		AND DEL_FLAG='N')  AS FLOAT)/CAST((SELECT SAMPLE_QUANTITY FROM wood.WH_RECEIPT_DTL WHERE ID=RECEIPT_ID) AS FLOAT),4)*100) >=80 AND
		(100 - ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
		WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
		AND DEL_FLAG='N')  AS FLOAT)/CAST((SELECT SAMPLE_QUANTITY FROM wood.WH_RECEIPT_DTL WHERE ID=RECEIPT_ID) AS FLOAT),4)*100) < 90
	THEN (100 - ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
		WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
		AND DEL_FLAG='N')  AS FLOAT)/CAST((SELECT SAMPLE_QUANTITY FROM wood.WH_RECEIPT_DTL WHERE ID=RECEIPT_ID) AS FLOAT),4)*100)+5
	ELSE
	(100 - ROUND(CAST((SELECT SUM(DEFECT_QTY) AS [DF_QTY] FROM wood.WOOD_INSPECTION 
		WHERE RECEIPT_ID IN (SELECT ID FROM wood.WH_RECEIPT_DTL WHERE WH_RECEIPT_ID=100000 AND DEL_FLAG='N')
		AND DEL_FLAG='N')  AS FLOAT)/CAST((SELECT SAMPLE_QUANTITY FROM wood.WH_RECEIPT_DTL WHERE ID=RECEIPT_ID) AS FLOAT),4)*100)
END AS [PAY_RATE],IT.VOLUMN AS [ITEM_VOLUMN],
	IT.VOLUMN*(SELECT PACKAGE_QUANTITY*PCS_PER_PACKAGE FROM wood.WH_RECEIPT_DTL WHERE ID = INS.RECEIPT_ID)*ROUND(CAST(DEFECT_QTY AS FLOAT)/CAST((SELECT SAMPLE_QUANTITY FROM wood.WH_RECEIPT_DTL WHERE ID=RECEIPT_ID)AS FLOAT),4) 
	AS [QC_VOLUMN],
	0 AS [WH_VOLUMN],
	dbo.FUNC_GET_PRICE_WOOD((SELECT RECEIPT_DATE FROM wood.WH_RECEIPT WHERE ID =100000),INS.ITEM_ID,(CASE WHEN HUMIDITY <=30 THEN 'U' ELSE 'K' END),(SELECT REGION_ID FROM base.VENDOR WHERE ID = (SELECT VENDOR_ID FROM wood.WH_RECEIPT WHERE ID = 100000))) AS [COM_PRICE]
FROM wood.WOOD_INSPECTION AS INS
INNER JOIN base.ITEM AS IT ON IT.ID = INS.ITEM_ID
---\
-- XONG 