CREATE TABLE nlg.PHIEUNHAPKHO(
	ID INT IDENTITY(100000,1) NOT NULL PRIMARY KEY,
	[GUID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[NUM] VARCHAR(300) NOT NULL,
	[MONTH] VARCHAR(300) NOT NULL,
	[YEAR] INT NOT NULL,
	[BIENSOXE] NVARCHAR(100) NULL,
	[DEL_FLAG] NVARCHAR(200) DEFAULT 'N',
	[HACAP] NVARCHAR(200) DEFAULT 'N',
	[TINHTIEN] NVARCHAR(200) DEFAULT 'N',
	[QC_STAFF] INT,
	[XUONGXENANG] NVARCHAR(200) DEFAULT 'N',
	[CREATE_DATE] DATETIME DEFAULT GETDATE(),
	[CREATE_BY] INT,
	[RECEIPT_DATE] DATETIME,
	[MANCC] INT,
	[MAKHO] INT,
	SP_OLD NVARCHAR(300)
)

CREATE TABLE nlg.PHIEUNHAPKHO_DT(
	ID INT IDENTITY(100000,1) NOT NULL PRIMARY KEY,
	[GUID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[SOPHIEU_ID] INT,
	[ID_QUICACH] INT,
	[SOBO] INT,
	[SOTHANHBO] INT,
	[NOTE] NVARCHAR(200),
	[CREATE_DATE] DATETIME DEFAULT GETDATE(),
	[DEL_FLAG] NVARCHAR(200),
	[SLMAU] INT,
	[DELAI] NVARCHAR(200) DEFAULT 'N',
	[DONGIA] INT,
	[DONGIATB] INT,
	[SOPHIEUTRAVE] INT,
	[MASP] NVARCHAR(10),
	DONGIA_LOAI FLOAT,
	INPUT_TYPE NVARCHAR(200),
	[CREATE_BY] INT,
	[ID_OLD] INT,
	NOTE_HC VARCHAR(30),
	[GOOD_QTY] INT,
	[PHIEU_TRAVE_ID] INT
)



CREATE TABLE nlg.QUICACH(
	ID INT IDENTITY(100000,1) NOT NULL PRIMARY KEY,
	[GUID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[CODE] NVARCHAR(30),
	[NAME] NVARCHAR(300),
	[DAI] INT,
	[RONG] INT,
	[DAY] INT,
	[VOLUMN] FLOAT,
	[GROUP_ID] INT,
	[USE_FLAG] NVARCHAR(200) DEFAULT 'Y'
)


CREATE TABLE nlg.HACAP(
	ID INT IDENTITY(100000,1) NOT NULL PRIMARY KEY,
	[GUID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[TYPEID] INT,
	[DEL_FLAG] NVARCHAR(10),
	[NOTE] NVARCHAR(300),
	[CREATE_DATE] DATETIME DEFAULT GETDATE(),
	[CREATE_BY] INT,
	[SL] INT,
	[DONGIA_CTY] INT,
	[DONGIA_LOAI] INT,
	[GAPDOI] NVARCHAR(10),
	[DETAIL_ID] INT,
	[MASP] NVARCHAR(300),
	[QUICACH_ID] INT,
	[ID_OLD] INT,
	[DONGIATB] int null
)

CREATE TABLE nlg.GROUP_QUICACH (
	ID INT IDENTITY(100000,1) NOT NULL PRIMARY KEY,
	[GUID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[CODE] NVARCHAR(300),
	[NAME]  NVARCHAR(300)

)
CREATE TABLE nlg.[MAKHO](
	[MAKHO] [nchar](10) NOT NULL,
	[TENKHO] [nvarchar](250) NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_AT] [datetime] NULL,
	[DEL_FLAG] [nchar](10) NULL,
	[TYPE] [nchar](10) NULL,
	[THUKHO] [nvarchar](50) NULL
)

CREATE TABLE nlg.[NLGO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MANVL] [nvarchar](255) NULL,
	[TENNVL] [nvarchar](255) NULL,
	[TROGIA] [nvarchar](255) NULL,
	[TENCHITIET] [nvarchar](255) NULL,
	[DAY] [nchar](10) NULL,
	[RONG] [nchar](10) NULL,
	[CAO] [nchar](10) NULL,
	[LOAI] [nvarchar](255) NULL,
	[NHOM] [nvarchar](50) NULL,
	[PHANLOAI] [nchar](10) NULL,
	[MANVLKHO] [nvarchar](50) NULL
)

CREATE TABLE nlg.[PLAN_NLG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](50) NULL,
	[MANCC] [nchar](10) NULL,
	[PLANQTY] [int] NULL,
	[DEL_FLAG] [nchar](10) NULL,
	[CREATE_BY] [nvarchar](50) NULL,
	[CREATED_AT] [datetime] NULL,
	[GROUP_CODE] [int] NULL,
	[NOTE] [nvarchar](550) NULL,
	[MONTH] INT,
	[YEAR] INT
)
CREATE TABLE nlg.[REQ_COST](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REQNO] [varchar](50) NOT NULL,
	[CREATE_BY] [nvarchar](50) NULL,
	[CREATED_AT] [datetime] NULL,
	[APPROVAL] [nchar](10) NULL,
	[APPROVAL_BY] [nvarchar](50) NULL,
	[APPROVAL_AT] [datetime] NULL,
	[REASON] [nvarchar](250) NULL,
	[DEL_FLAG] [nchar](10) NULL,
	[UPDATE_BY] [nvarchar](50) NULL,
	[UPDATE_TIME] [datetime] NULL
)
CREATE TABLE nlg.[STAFF](
	[ID] [nvarchar](50) NOT NULL,
	[NAME] [nvarchar](50) NULL,
	[DEPARTMENT] [nvarchar](50) NULL
)
CREATE TABLE nlg.[TINHTIEN](
	[SOPHIEU] [varchar](20) NOT NULL,
	[XUATHOADON] [nchar](10) NULL,
	[HOTROVANCHUYEN] [int] NULL,
	[HOTROKHAC] [int] NULL,
	[TONGTHANHTOAN] [int] NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[APPROVAL] [nvarchar](50) NULL,
	[CREATED_AT] [datetime] NULL,
	[KLKHO] [float] NULL,
	[KLQC] [float] NULL,
	[DONGIATB] [int] NULL,
	[TYLECHINHPHAM] [float] NULL,
	[TONGTIENCHUATHUE] [int] NULL,
	[NHANVIEN] [nvarchar](50) NULL,
	[COC] [nchar](10) NULL
)
CREATE TABLE nlg.[TYPE_HACAP](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TYPENAME] [nvarchar](50) NULL,
	[BGCOLOR] [nvarchar](50) NULL,
	[ICON] [nvarchar](50) NULL
)
CREATE TABLE nlg.[TROGIA](
	[QUICACH] [nchar](20) NULL,
	[CREATED_AT] [datetime] NULL,
	[DEL_FLAG] [nchar](10) NULL,
	[SPECIAL] [nchar](10) NULL,
	[QT] [int] NULL,
	[HT] [int] NULL,
	[NA] [int] NULL,
	[QB] [int] NULL,
	[TH] [int] NULL
)
CREATE TABLE nlg.[VUNG](
	[MAVUNG] [nchar](10) NOT NULL,
	[TENVUNG] [nvarchar](50) NULL
)
CREATE TABLE nlg.[VUNGVANCHUYEN](
	[MAVUNG] [nchar](10) NOT NULL,
	[HESONHAN] [int] NULL,
	[DEL_FLAG] [nchar](10) NULL
)
CREATE TABLE nlg.[DINH_MUC_KHO](
	ID INT IDENTITY(100000,1) NOT NULL PRIMARY KEY,
	[GUID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[MAKHO] INT,
	[GROUP_QUI_CACH_ID] INT,
	[KHOILUONG] FLOAT
)
CREATE TABLE nlg.[PROVIDERS](
	ID INT IDENTITY(100000,1) NOT NULL PRIMARY KEY,
	[GUID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[CODE] varchar(10) NOT NULL,
	[NAME] varchar(250) NULL,
	[ADDRESS] [nvarchar](150) NULL,
	[STAFF] INT NULL,
	[DEL_FLAG] [nchar](10) NULL,
	[VUNG] [nchar](10) NULL,
	[VUNG2] varchar(10) NULL,
	[COHD] varchar(10) NULL,
	[COC] varchar(10) NULL,
	[INSERT_BY] [nvarchar](50) NULL,
	[INSERT_TIME] [datetime] NULL,
	[UPDATE_BY] [nvarchar](50) NULL,
	[UPDATE_TIME] [datetime] NULL
)
CREATE TABLE nlg.[CONFIG_TYLE](
	[TYLE] [float] NULL,
	[HESO] [int] NULL,
	[UPDATE_TIME] [datetime] NULL,
	[UPDATE_BY] [nvarchar](50) NULL,
	[TYPE] [nchar](10) NULL
)
CREATE TABLE [NLG].[CF_GIA_LOAI](
	[CODE] [nchar](10) NULL,
	[NAME] [nvarchar](50) NULL,
	[COST] [int] NULL,
	[TYPE] [int] NULL
)
CREATE TABLE [NLG].[PHIEUTRAVE](
	[ID] INT IDENTITY(100000,1) PRIMARY KEY ,
	[GUID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[SOPHIEUTRAVE] [nvarchar](50) NULL,
	[MANCC] [nvarchar](50) NULL,
	[CREATED_AT] [date] NULL,
	[CREATE_BY] [nvarchar](50) NULL,
	[NOTE] [nvarchar](150) NULL,
	[FROMSL] [nvarchar](10) NULL
)

CREATE TABLE [NLG].[BANGGIANVL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MASP] [nvarchar](50) NULL,
	[COST] [float] NULL,
	[UPDATE_DATE] [date] NULL,
	[INSERT_BY] [nvarchar](50) NULL,
	[USE_FLAG] [nchar](10) NULL,
	[VUNG] [nchar](10) NULL,
	[REQNO] [varchar](50) NULL,
	[APPLY_DATE] [date] NULL
)

INSERT INTO nlg.CF_GIA_LOAI
SELECT * FROM WoodslandNLG.dbo.CF_GIA_LOAI

INSERT INTO nlg.CONFIG_TYLE
SELECT * FROM WoodslandNLG.dbo.CONFIG_TYLE

INSERT INTO  NLG.NLGO
SELECT * FROM WoodslandNLG.DBO.NLGO

INSERT INTO NLG.VUNG
SELECT * FROM WoodslandNLG.dbo.VUNG

INSERT INTO NLG.VUNGVANCHUYEN
SELECT * FROM WoodslandNLG.dbo.VUNGVANCHUYEN

INSERT INTO nlg.BANGGIANVL
SELECT * FROM WoodslandNLG.dbo.BANGGIANVL
---
INSERT INTO nlg.[TYPE_HACAP]([TYPENAME]) VALUES(N'Chính Phẩm B')
INSERT INTO nlg.[TYPE_HACAP]([TYPENAME]) VALUES(N'Hạ Cấp 1')
INSERT INTO nlg.[TYPE_HACAP]([TYPENAME]) VALUES(N'Hạ Cấp 2')
INSERT INTO nlg.[TYPE_HACAP]([TYPENAME]) VALUES(N'Hạ Cấp 3')
INSERT INTO nlg.[TYPE_HACAP]([TYPENAME]) VALUES(N'Hạ Cấp 4')
INSERT INTO nlg.[TYPE_HACAP]([TYPENAME]) VALUES(N'Hạ Cấp 5')
INSERT INTO nlg.[TYPE_HACAP]([TYPENAME]) VALUES(N'Hàng Loại B')
INSERT INTO nlg.[TYPE_HACAP]([TYPENAME]) VALUES(N'Hàng Loại C')
INSERT INTO nlg.[TYPE_HACAP]([TYPENAME]) VALUES(N'Hàng Loại')