CREATE OR ALTER TRIGGER UPDATE_GOOD_QTY_PNK_DT ON nlg.HACAP
AFTER INSERT,UPDATE
AS
BEGIN
	DECLARE @NEW_GOOD_QTY INT,@TONG_SL_HA_CAP INT,@SO_TAM_MAU INT
	SELECT @SO_TAM_MAU = SLMAU FROM NLG.PHIEUNHAPKHO_DT WHERE ID = (SELECT DETAIL_ID FROM inserted)
	SELECT @TONG_SL_HA_CAP = SUM(SL) FROM NLG.HACAP
	WHERE DETAIL_ID = (SELECT DETAIL_ID FROM inserted)
	SELECT @NEW_GOOD_QTY = @SO_TAM_MAU - @TONG_SL_HA_CAP

	UPDATE NLG.PHIEUNHAPKHO_DT SET GOOD_QTY = @NEW_GOOD_QTY WHERE ID =  (SELECT DETAIL_ID FROM inserted)
END
