CREATE TRIGGER ADD_DEPARTMENT_FOR_SA_USER ON base.DEPARTMENT
AFTER INSERT
AS 
BEGIN
	INSERT INTO base.ROLE_VALUE([GUID],[ROLE_ID],[ROLE_TYPE_ID],[VALUE]) VALUES(NEWID(),100400,100001,(SELECT ID FROM inserted))
	INSERT INTO base.ROLE_VALUE([GUID],[ROLE_ID],[ROLE_TYPE_ID],[VALUE]) VALUES(NEWID(),100400,100002,(SELECT ID FROM inserted))
END
--TRIGGER ADD MENU
CREATE or ALTER TRIGGER [base].ADD_MENU_DESKTOP_FOR_SA_USER ON base.MENU
AFTER INSERT
AS 
BEGIN
	DECLARE @ROLE_TYPE_ID INT,@TYPE_MENU VARCHAR(30)
	SELECT @TYPE_MENU = [TYPE] FROM inserted
	IF(@TYPE_MENU='desktop')
		SELECT @ROLE_TYPE_ID = 100006
	ELSE
		SELECT @ROLE_TYPE_ID =100009
	INSERT INTO base.ROLE_VALUE([GUID],[ROLE_ID],[ROLE_TYPE_ID],[VALUE]) VALUES(NEWID(),100400,@ROLE_TYPE_ID,(SELECT ID FROM inserted))
	
END