
GO
SET IDENTITY_INSERT nlg.GROUP_QUICACH ON;
GO
DECLARE @LoopCounter INT,@MaxID INT,@MinID Int,@NAME NVARCHAR(300),@OLD_ID INT

SELECT @MaxID = MAX(id),@MinID = min(ID) FROM  WoodslandNLG.dbo.GROUP_CODE
SET @LoopCounter =@MinID
WHILE (@LoopCounter IS NOT NULL AND @LoopCounter <= @MaxID)
BEGIN
	SELECT @OLD_ID = ID,@NAME=[NAME] FROM WoodslandNLG.dbo.GROUP_CODE WHERE ID = @LoopCounter
	INSERT INTO nlg.GROUP_QUICACH([ID],[GUID],[CODE],[NAME]) VALUES(@OLD_ID,NEWID(),@NAME,@NAME)
	SELECT @LoopCounter= MIN(ID) FROM  WoodslandNLG.dbo.GROUP_CODE WHERE ID >@LoopCounter
END 