SELECT * FROM NLG.QUICACH
TRUNCATE TABLE NLG.QUICACH
SELECT * FROM WoodslandNLG.dbo.BOM
UPDATE  WoodslandNLG.dbo.BOM SET NHOM = 100136 WHERE NHOM='XXX'

-- addd identity column
alter table WoodslandNLG.dbo.BOM
add ID int identity(1,1)


DECLARE @LoopCounter INT,@MaxID INT,@MinID Int,@NAME NVARCHAR(300),@CODE VARCHAR(300),
@DAY INT,@RONG INT,@DAI INT,@KL FLOAT,@GROUP_ID INT,@USE_FLAG VARCHAR(30)

SELECT @MaxID = MAX(id),@MinID = min(ID) FROM  WoodslandNLG.dbo.BOM
SET @LoopCounter =@MinID
WHILE (@LoopCounter IS NOT NULL AND @LoopCounter <= @MaxID)
BEGIN
	SELECT @CODE = [CODE],@NAME=[NAME],@DAY = [DAY],@RONG= RONG,@DAI = [DAI],
	@KL = POWER(CAST(10 AS FLOAT),CAST(-9 AS FLOAT))*[DAY]*[RONG]*[DAI],
	@GROUP_ID = NHOM,@USE_FLAG=USEFLAG
	FROM WoodslandNLG.dbo.BOM WHERE ID = @LoopCounter
	INSERT INTO nlg.QUICACH([GUID],[CODE],[NAME],[DAY],[RONG],[DAI],[VOLUMN],[GROUP_ID],[USE_FALG]) 
	VALUES(NEWID(),@CODE,@NAME,@DAY,@RONG,@DAI,@KL,@GROUP_ID,@USE_FLAG)


	SELECT @LoopCounter= MIN(ID) FROM  WoodslandNLG.dbo.BOM WHERE ID >@LoopCounter
END 