
-- addd identity column
alter table WoodslandNLG.dbo.PHIEUNHAPKHO
add ID int identity(1,1)

DECLARE @LoopCounter INT,@MaxID INT,@MinID Int,@SOPHIEU VARCHAR(300),@NUM INT,@NUM_FORMAT VARCHAR(30),
@MONTH INT,@MONTH_FORMAT VARCHAR(30),@YEAR INT,@MANCC NVARCHAR(30),@MAKHO VARCHAR(30)

SELECT @MaxID = MAX(id),@MinID = min(ID) FROM  WoodslandNLG.dbo.PHIEUNHAPKHO
 WHERE DATEPART(MONTH,CREATED_AT)>7 AND DATEPART(YEAR,CREATED_AT)>=2019
SET @LoopCounter =@MinID
WHILE (@LoopCounter IS NOT NULL AND @LoopCounter <= @MaxID)
BEGIN
	DECLARE @BSX VARCHAR(300),@DEL_FLAG VARCHAR(300),@HACAP VARCHAR(300),@TINHTIEN VARCHAR(300)
	,@CREATED_DATE DATETIME,@RECEIPT_DATE DATETIME,@XENANG VARCHAR(30),@MANCC_CODE VARCHAR(40),@MAKHO_CODE VARCHAR(30),@NUM2 VARCHAR(30)
	SELECT @SOPHIEU = SOPHIEU,@MONTH =DATEPART(MONTH,CREATED_AT),@YEAR=DATEPART(YEAR,CREATED_AT) ,
	@BSX = BIENSOXE,@DEL_FLAG = DEL_FLAG,@HACAP= ALLOWHACAP,@TINHTIEN = ALLOWTINHTIEN,@CREATED_DATE = ACTUALDATE,
	@RECEIPT_DATE = CREATED_AT,@XENANG = XUONGXENANG,@MANCC_CODE= MANCC,@MAKHO_CODE=MAKHO
	FROM  WoodslandNLG.dbo.PHIEUNHAPKHO WHERE ID= @LoopCounter
	SELECT @NUM = CONVERT(int,TRIM('.' FROM CONVERT(VARCHAR(40),SUBSTRING(@SOPHIEU,CHARINDEX('.',@SOPHIEU)+1,CHARINDEX('/',@SOPHIEU)-CHARINDEX('.',@SOPHIEU)-1))))
	--INSERT INTO nlg.PHIEUNHAPKHO_C([NUM])
	--2019.01/10VH
	--SUBSTRING(@SOPHIEU,CHARINDEX('.',@SOPHIEU)+1,CHARINDEX('/',@SOPHIEU)-CHARINDEX('.',@SOPHIEU)-1)
	SELECT @NUM_FORMAT = CONVERT(VARCHAR(30),@NUM)
	SELECT @MONTH_FORMAT = CONVERT(VARCHAR(30),@MONTH)
	IF(@NUM <10)
		SELECT @NUM_FORMAT = '0'+CONVERT(VARCHAR(30),@NUM)
	IF(@MONTH<10)
		SELECT @MONTH_FORMAT='0'+CONVERT(VARCHAR(30),@MONTH)
	
	--LOOKUP NCC
	SELECT @MANCC = ID FROM NLG.PROVIDERS WHERE CODE= @MANCC_CODE
	SELECT @MAKHO = ID FROM base.DEPARTMENT WHERE CODE = @MAKHO_CODE AND TYPE2='stock2'
	PRINT(@NUM_FORMAT)
	INSERT INTO nlg.PHIEUNHAPKHO_C([NUM],[MONTH],[YEAR],[BIENSOXE],[DEL_FLAG],[HACAP],[TINHTIEN],[QC_STAFF],[XUONGXENANG],[CREATE_DATE],
	RECEIPT_DATE,MANCC,[MAKHO],[SP_OLD])
	VALUES(@NUM_FORMAT,@MONTH_FORMAT,@YEAR,@BSX,@DEL_FLAG,@HACAP,@TINHTIEN,100400,@XENANG,@CREATED_DATE,@RECEIPT_DATE,@MANCC,@MAKHO,@SOPHIEU)

	SELECT @LoopCounter= MIN(ID) FROM  WoodslandNLG.dbo.PHIEUNHAPKHO WHERE ID >@LoopCounter
END 

SELECT * FROM WoodslandNLG.DBO.PHIEUNHAPKHO WHERE DATEPART(MONTH,CREATED_AT)>7 AND DATEPART(YEAR,CREATED_AT)>=2019
select * from nlg.PHIEUNHAPKHO_C
select * from nlg.PHIEUNHAPKHO 
SELECT * FROM NLG.PROVIDERS

truncate table nlg.PHIEUNHAPKHO_C

SELECT TRIM('.' FROM '16')