DECLARE @LoopCounter INT,@MaxID INT,@MinID Int
select @MaxID = MAX(ID) ,@MinID = min(id)  from WoodslandNLG.dbo.HACAP
select @LoopCounter = @MinID
WHILE (@LoopCounter <= @MaxID)
BEGIN
	DECLARE @TYPEID INT,@DEL_FLAG VARCHAR(30),@NOTE NVARCHAR(300),@CREATED_DATE DATETIME,
	@SL INT,@DONGIA_CTY INT,@DONGIA_LOAI INT,@GAPDOI VARCHAR(30),@DETAIL_ID INT,@MASP VARCHAR(300),@ID_OLD INT,
	@QUI_CACH_ID INT,@OLD_DT_ID INT
	SELECT @TYPEID =[TYPE],@DEL_FLAG= DEL_FLAG,@NOTE=NOTE,
	@CREATED_DATE=CREATED_AT,@SL=SOTHANH,@DONGIA_CTY=DONGIA_CTY,@DONGIA_LOAI=DONGIA_LOAI
	 ,@GAPDOI =GAPDOI,@OLD_DT_ID=ID_DT,@ID_OLD=ID,@QUI_CACH_ID= (SELECT TOP 1 ID FROM nlg.QUICACH WHERE [DAY]=HC.DAY AND RONG=HC.RONG AND DAI = HC.CAO)  
	 FROM WoodslandNLG.dbo.HACAP  AS HC 
	 WHERE ID = @LoopCounter
	 INSERT INTO nlg.HACAP([TYPEID],[DEL_FLAG],[NOTE],[CREATE_DATE],[CREATE_BY],[SL],
	 [DONGIA_CTY],[DONGIA_LOAI],[GAPDOI],[MASP],[ID_OLD],[QUICACH_ID],[OLD_DT_ID])
	 VALUES(@TYPEID,@DEL_FLAG,@NOTE,@CREATED_DATE,100400,@SL,@DONGIA_CTY,@DONGIA_LOAI,@GAPDOI,@MASP,@ID_OLD,@QUI_CACH_ID,@OLD_DT_ID)
	SELECT @LoopCounter = MIN(ID) FROM WoodslandNLG.dbo.HACAP WHERE ID>@LoopCounter
END
SELECT 1 AS LLL
SELECT * FROM nlg.HACAP
SELECT HC.*  FROM nlg.HACAP AS HC
INNER JOIN NLG.PHIEUNHAPKHO_DT AS PT ON PT.ID_OLD = HC.OLD_DT_ID

UPDATE HC
SET HC.DETAIL_ID = PT.ID
FROM
nlg.HACAP AS HC
INNER JOIN NLG.PHIEUNHAPKHO_DT AS PT ON PT.ID_OLD = HC.OLD_DT_ID

--SELECT TOP 1 * FROM NLG.HACAP
--SELECT TOP 1 * FROM WoodslandNLG.dbo.HACAP 