
INSERT INTO wood.WOOD_TYPE([CODE],[NAME]) VALUES('KEO',N'Gỗ keo')
INSERT INTO wood.WOOD_TYPE([CODE],[NAME]) VALUES('KF1',N'Gỗ keo F1')
INSERT INTO wood.WOOD_TYPE([CODE],[NAME]) VALUES('BD',N'Gỗ bạch đàn')