CREATE OR ALTER PROC Proc_addEvent
@CHANNEL NVARCHAR(200),
@MESSAGE NVARCHAR(MAX)
AS
BEGIN
SET XACT_ABORT ON
BEGIN TRANSACTION
	DECLARE @NO INT
	DECLARE @GUID uniqueidentifier = NEWID()

	SELECT TOP(1) @NO = [NO]
	FROM app.[EVENT]
	WHERE CAST(CREATE_DATE AS DATE) = CAST(GETDATE() AS DATE)
	AND CHANNEL = @CHANNEL
	ORDER BY ID DESC

	IF(@NO IS NULL)
		BEGIN
			SET @NO = 0
		END
	SET @NO = @NO + 1


	INSERT INTO app.[EVENT] ([GUID],[NO],[CHANNEL], [MESSAGE])
	VALUES (@GUID,@NO,@CHANNEL,@MESSAGE)


	SELECT @NO AS 'no'
	FROM app.[EVENT]
	WHERE [GUID] = @GUID
COMMIT
END