-- Báo cáo QC xử lý hàng theo tuần
SELECT
GD.WEEK N'Tuần',
GD.[DATE] N'Ngày',
S.CODE N'Mã tổ QC',
D.NAME N'Kho đến',
PT.NAME N'Loại lỗi',
RM.NAME N'Biện pháp xử lý',
I.NAME N'Chi tiết/cụm',
IIP.QUANTITY N'Số lượng',
CB.LAST_NAME N'Người tạo',
P.CREATE_DATE N'Ngày tạo',
VB.LAST_NAME N'Người nhận',
P.VERIFY_DATE N'Ngày nhận'
FROM prod.PACKAGE P
LEFT JOIN prod.PACKAGE_TYPE PT ON PT.ID = P.TYPE_ID
LEFT JOIN prod.REMEDIES RM ON RM.ID = P.REMEDIES_ID
LEFT JOIN prod.ITEM_IN_PACKAGE IIP ON IIP.PACKAGE_ID = P.ID
LEFT JOIN base.DEPARTMENT S ON S.ID = P.SOURCE_ID
LEFT JOIN base.DEPARTMENT D ON D.ID = P.DESTINATION_ID
LEFT JOIN base.ITEM I ON I.ID = IIP.ITEM_ID
LEFT JOIN base.GLOBAL_DATE GD ON GD.[DATE] = CAST(P.CREATE_DATE AS DATE)
LEFT JOIN base.ACCOUNT CB ON CB.ID = P.CREATE_BY
LEFT JOIN base.ACCOUNT VB ON VB.ID = P.VERIFY_BY
WHERE S.[TYPE] = 'QC'
AND P.CREATE_DATE BETWEEN @FROM AND @TO

--SELECT * FROM base.DEPARTMENT

-- Báo cáo hàng đến kho QC
SELECT 
GD.WEEK N'Tuần',
GD.[DATE] N'Ngày',
S.NAME N'Tổ',
D.CODE N'Mã kho QC',
I.NAME N'Chi tiết/cụm',
IIP.QUANTITY N'Số lượng',
CB.LAST_NAME N'Người tạo',
P.CREATE_DATE N'Ngày tạo',
VB.LAST_NAME N'Người nhận',
P.VERIFY_DATE N'Ngày nhận'
FROM prod.PACKAGE P
LEFT JOIN prod.ITEM_IN_PACKAGE IIP ON IIP.PACKAGE_ID = P.ID
LEFT JOIN base.DEPARTMENT S ON S.ID = P.SOURCE_ID
LEFT JOIN base.DEPARTMENT D ON D.ID = P.DESTINATION_ID
LEFT JOIN base.GLOBAL_DATE GD ON GD.[DATE] = CAST(P.CREATE_DATE AS DATE)
LEFT JOIN base.ITEM I ON I.ID = IIP.ITEM_ID
LEFT JOIN base.ACCOUNT CB ON CB.ID = P.CREATE_BY
LEFT JOIN base.ACCOUNT VB ON VB.ID = P.VERIFY_BY
WHERE D.[TYPE] = 'QC'