DECLARE @ACCOUNT_ID INT = 100400
/*
DELETE base.ROLE_VALUE
WHERE ROLE_ID = @ACCOUNT_ID
AND ROLE_TYPE_ID = 100006 OR ROLE_TYPE_ID = 100009
*/

INSERT INTO base.ROLE_VALUE(GUID,ROLE_ID,ROLE_TYPE_ID, VALUE)
SELECT NEWID(),100400,100006,M.ID
FROM base.MENU M
LEFT JOIN (
	SELECT VALUE FROM base.ACCOUNT A
	LEFT JOIN base.ROLE_VALUE RV ON RV.ROLE_ID = A.ROLE_ID
	WHERE A.ID = 100400
	AND RV.ROLE_TYPE_ID = 100006
)A ON A.VALUE = M.ID
WHERE A.VALUE IS NULL
AND M.TYPE = 'desktop'

--INSERT INTO base.ROLE_VALUE(GUID,ROLE_ID,ROLE_TYPE_ID, VALUE)
SELECT NEWID(),@ACCOUNT_ID,100009,M.ID
FROM base.MENU M
LEFT JOIN (
	SELECT VALUE FROM base.ACCOUNT A
	LEFT JOIN base.ROLE_VALUE RV ON RV.ROLE_ID = A.ROLE_ID
	WHERE A.ID = @ACCOUNT_ID
	AND RV.ROLE_TYPE_ID = 100009
)A ON A.VALUE = M.ID
WHERE A.VALUE IS NULL
AND M.TYPE = 'mobile'


INSERT INTO base.ROLE_VALUE(GUID,ROLE_ID,ROLE_TYPE_ID, VALUE)
VALUES (NEWID(),@ACCOUNT_ID,100008 , N'Mobile user'),
(NEWID(),@ACCOUNT_ID,100008 , N'Supper user')


DELETE base.ROLE_VALUE
WHERE ROLE_ID = 100400
AND ROLE_TYPE_ID = 100001
INSERT INTO base.ROLE_VALUE(GUID,ROLE_ID,ROLE_TYPE_ID, VALUE)
SELECT NEWID(),100400,100001,D.ID
FROM base.DEPARTMENT D
LEFT JOIN (
	SELECT VALUE FROM base.ACCOUNT A
	LEFT JOIN base.ROLE_VALUE RV ON RV.ROLE_ID = A.ROLE_ID
	WHERE A.ID = 100400
	AND RV.ROLE_TYPE_ID = 100001 
) A ON A.VALUE = D.ID
WHERE A.VALUE IS NULL

DELETE base.ROLE_VALUE
WHERE ROLE_ID = 100400
AND ROLE_TYPE_ID = 100002
INSERT INTO base.ROLE_VALUE(GUID,ROLE_ID,ROLE_TYPE_ID, VALUE)
SELECT NEWID(),100400,100002,D.ID
FROM base.DEPARTMENT D
LEFT JOIN (
	SELECT VALUE FROM base.ACCOUNT A
	LEFT JOIN base.ROLE_VALUE RV ON RV.ROLE_ID = A.ROLE_ID
	WHERE A.ID = 100400
	AND RV.ROLE_TYPE_ID = 100002
) A ON A.VALUE = D.ID
WHERE A.VALUE IS NULL

INSERT INTO base.ROLE_VALUE(GUID,ROLE_ID,ROLE_TYPE_ID, VALUE)
SELECT NEWID(),@ACCOUNT_ID,100007,C.ID
FROM base.CATEGORY C
LEFT JOIN (
	SELECT VALUE FROM base.ACCOUNT A
	LEFT JOIN base.ROLE_VALUE RV ON RV.ROLE_ID = A.ROLE_ID
	WHERE A.ID = @ACCOUNT_ID
	AND RV.ROLE_TYPE_ID = 100007
) A ON A.VALUE = C.ID
WHERE A.VALUE IS NULL




/*
DELETE base.ROLE_VALUE
WHERE ROLE_ID = 100393
*/

/*


SELECT * FROM base.ROLE_VALUE
WHERE ROLE_ID = 100393

SELECT * FROM base.CATEGORY

SELECT * 
FROM base.ROLE_TYPE


SELECT * FROM base.ROLE_VALUE

*/