const orders = require("./orders");
const requests = require("./requests");
const messages = require("./messages");
const orderMetas = require("./orderMetas");
const calendarWork = require("./calendarWork");
const userRegistration = require("./userRegistration");
const cars = require("./cars");
const department = require("./departmentForm");
const formRequests = require("./formRequests");
const reportQuitJob = require("./reportQuitJob");
const notification = require("./notification");
const meetingRoom = require("./meetingRoom");
const formRegister = require("./formRegister");
const roleDepartment = require("./roleDepartment");
const bookMeeting = require("./bookMeeting");
const bookMeetingApproved = require("./bookMeetingApproved");
const menu = require("./menu");
const account = require("./account");
const document = require("./document");
const forgetPassword = require("./forgetPassword");
const payslip = require("./payslip");

module.exports = router => {
    orders(router);
    orderMetas(router);
    messages(router);
    requests(router);
    calendarWork(router);
    userRegistration(router);
    cars(router);
    department(router);
    formRequests(router);
    roleDepartment(router);
    reportQuitJob(router);
    notification(router);
    meetingRoom(router);
    formRegister(router);
    bookMeeting(router);
    bookMeetingApproved(router);
    menu(router);
    account(router);
    forgetPassword(router);
    document(router);
    payslip(router);
    return router;
};