DECLARE @DATE DATETIME = '2019-01-01'
DECLARE @TO INT = 1800 --5 năm

WHILE @TO > 0
BEGIN
SET @TO = @TO - 1
SET @DATE = @DATE + 1

INSERT INTO base.[GLOBAL_DATE]([GUID],[DATE],CODE,[YEAR],[MONTH],[WEEK],[DAY],WEEK_DAY,[YEAR_MONTH],[YEAR_WEEK])
SELECT NEWID() , @DATE,
CASE 
	WHEN MONTH(@DATE) < 10 AND DAY(@DATE) < 10 THEN CONCAT(YEAR(@DATE),'0',MONTH(@DATE),'0', DAY(@DATE))
	WHEN MONTH(@DATE) < 10 AND DAY(@DATE) > 10 THEN CONCAT(YEAR(@DATE),'0',MONTH(@DATE), DAY(@DATE))
	WHEN MONTH(@DATE) < 10 AND DAY(@DATE) = 10 THEN CONCAT(YEAR(@DATE),'0',MONTH(@DATE), DAY(@DATE))
	WHEN MONTH(@DATE) > 10 AND DAY(@DATE) < 10 THEN CONCAT(YEAR(@DATE),MONTH(@DATE),'0', DAY(@DATE))
	WHEN MONTH(@DATE) > 10 AND DAY(@DATE) > 10 THEN CONCAT(YEAR(@DATE),MONTH(@DATE), DAY(@DATE))
	WHEN MONTH(@DATE) > 10 AND DAY(@DATE) = 10 THEN CONCAT(YEAR(@DATE),MONTH(@DATE), DAY(@DATE))
	WHEN MONTH(@DATE) = 10 AND DAY(@DATE) < 10 THEN CONCAT(YEAR(@DATE),MONTH(@DATE),'0', DAY(@DATE))
	WHEN MONTH(@DATE) = 10 AND DAY(@DATE) > 10 THEN CONCAT(YEAR(@DATE),MONTH(@DATE), DAY(@DATE))
	WHEN MONTH(@DATE) = 10 AND DAY(@DATE) = 10 THEN CONCAT(YEAR(@DATE),MONTH(@DATE), DAY(@DATE))
END AS CODE,
YEAR(@DATE),
MONTH(@DATE),
DATEPART(WK,@DATE),
DAY(@DATE),
CASE
	WHEN DATEPART(WEEKDAY, @DATE) = 1 THEN N'Chủ nhật'
	WHEN DATEPART(WEEKDAY, @DATE) = 2 THEN N'Thứ 2'
	WHEN DATEPART(WEEKDAY, @DATE) = 3 THEN N'Thứ 3'
	WHEN DATEPART(WEEKDAY, @DATE) = 4 THEN N'Thứ 4'
	WHEN DATEPART(WEEKDAY, @DATE) = 5 THEN N'Thứ 5'
	WHEN DATEPART(WEEKDAY, @DATE) = 6 THEN N'Thứ 6'
	WHEN DATEPART(WEEKDAY, @DATE) = 7 THEN N'Thứ 7'
END AS WEEK_DAY,
CASE 
	WHEN MONTH(@DATE) < 10 THEN CONCAT(YEAR(@DATE),'0',MONTH(@DATE))
	ELSE CONCAT(YEAR(@DATE),MONTH(@DATE))
END AS YEAR_MONTH,
CASE 
	WHEN DATEPART(WK,@DATE) < 10 THEN CONCAT(YEAR(@DATE),'0',DATEPART(WK,@DATE))
	ELSE CONCAT(YEAR(@DATE),DATEPART(WK,@DATE))
END AS YEAR_WEEK

END
