DELETE dbo.PALLET
WHERE [WEEK] < 45
GO

DELETE IIP
FROM dbo.ITEM_IN_PALLET IIP
LEFT JOIN dbo.PALLET P ON P.ID = IIP.PALLET_ID
WHERE P.ID IS NULL

DELETE SOP 
FROM dbo.STEP_OF_PALLET SOP
LEFT JOIN dbo.PALLET PL ON PL.ID = SOP.PALLET_ID
WHERE PL.ID IS NULL
GO

DELETE P
FROM dbo.PACKAGE P
WHERE P.CREATE_DATE < '2019-11-04'
GO

DELETE P
FROM dbo.PACKAGE P
LEFT JOIN dbo.STEP_OF_PALLET SOP ON SOP.ID = P.STEP_OF_PALLET_ID
WHERE SOP.ID IS NULL
AND P.STEP_OF_PALLET_ID IS NOT NULL
GO

DELETE IIP
FROM dbo.ITEM_IN_PACKAGE IIP
LEFT JOIN dbo.PACKAGE P ON P.ID = IIP.PACKAGE_ID
WHERE P.ID IS NULL
GO

DELETE MIP
FROM dbo.MATERIALS_IN_PACKAGE MIP
LEFT JOIN dbo.ITEM_IN_PACKAGE IIP ON IIP.ID = MIP.ITEM_IN_PACKAGE_ID
WHERE IIP.ID IS NULL
GO

DELETE PS
FROM dbo.PALLET_SUPPLIES PS
LEFT JOIN dbo.STEP_OF_PALLET SOP ON SOP.ID = PS.STEP_OF_PALLET_ID
WHERE SOP.ID IS NULL
GO

TRUNCATE TABLE dbo.[DEPENDENT]