SELECT * FROM dbo.[PALLET]
SELECT * FROM dbo.[ITEM_IN_PALLET]

SELECT * FROM dbo.[STEP_OF_PALLET]
SELECT * FROM dbo.[PACKAGE]

SELECT * FROM dbo.[ITEM_IN_PACKAGE]
SELECT * FROM dbo.[MATERIALS_IN_PACKAGE]

