CREATE OR ALTER FUNCTION wood.Func_get_LuonLi_Rate(
@RECEIPT_DLT_ID INT
)
RETURNS FLOAT
AS
BEGIN
	IF EXISTS (SELECT * FROM WOOD.WOOD_INSPECTION WHERE INPUT_TYPE_ID=100019 AND RECEIPT_ID=@RECEIPT_DLT_ID )
	BEGIN
		RETURN (SELECT TOP 1 PAY_RATE FROM wood.WOOD_INSPECTION WHERE RECEIPT_ID=@RECEIPT_DLT_ID AND INPUT_TYPE_ID=100019) 
	END
	RETURN 0
END
