CREATE OR ALTER FUNCTION wood.Func_get_Rate_A(
@RECEIPT_DLT_ID INT
)
RETURNS FLOAT
AS
BEGIN
	DECLARE @INPUT_TYPE_ID INT,@TOTAL_DEFECT_QTY INT,@SAMPLE_QTY INT
	SELECT @SAMPLE_QTY = SAMPLE_QTY FROM wood.WOOD_INSP WHERE RECEIPT_ID=@RECEIPT_DLT_ID
	SELECT @INPUT_TYPE_ID = INPUT_TYPE_ID FROM wood.WH_RECEIPT_DTL WHERE ID = @RECEIPT_DLT_ID
	IF @INPUT_TYPE_ID = 100000
	BEGIN
	-- NẾU NHẬP KHO LÀ HÀNG A
	-- TÍNH TỔNG SỐ TẤM LOẠI CỦA HÀNG LOẠI B VÀ C
	-- KHÔNG TÍNH HÀNG NON LI, LƯỢN LI, ẨM(HÀNG TƯƠI)
		SELECT @TOTAL_DEFECT_QTY = SUM(DEFECT_QTY) FROM WOOD.WOOD_INSPECTION WHERE RECEIPT_ID=@RECEIPT_DLT_ID AND INPUT_TYPE_ID IN(100001,100015)
		RETURN CAST((@SAMPLE_QTY-@TOTAL_DEFECT_QTY) AS FLOAT)/CAST(@SAMPLE_QTY AS FLOAT)
	END
	RETURN 0
END