

-- THÊM CỘT MODULE VÀO BẢNG PHIẾU NHẬP KHO
ALTER TABLE wood.WH_RECEIPT
add MODULE NVARCHAR(300)

-- THÊM KHO TRƯỚC SẤY CHO THUẬN HƯNG
INSERT INTO base.DEPARTMENT([GUID],[CODE],[TYPE],[PARENT_ID],[NAME],[TYPE2]) VALUES(NEWID(),'TH','Kho',100000,N'Kho gỗ thô','stock')

-- THÊM KHO GỖ THÔ VÀO BỘ PHẬN LÀM VIỆC CHO TÀI KHOẢN SA
INSERT INTO base.ROLE_VALUE([GUID],[ROLE_ID],[ROLE_TYPE_ID],[VALUE]) VALUES(NEWID(),100400,100001,100227)
 
--THÊM CHỨC NĂNG MOBILE
-- THÊM CHỨC NĂNG NHẬP KHO VÀ NGHIỆM THU
INSERT INTO base.MENU([GUID],[PARENT_ID],[CODE],[NAME],[PATH],[TYPE]) VALUES(NEWID(),100001,'NK',N'Nhập gỗ','/wood-warehouse-receipts','mobile')
INSERT INTO base.MENU([GUID],[PARENT_ID],[CODE],[NAME],[PATH],[TYPE]) VALUES(NEWID(),100001,'NK',N'Nghiệm thu(gỗ)','/wood-warehouse-receipts?type=qc','mobile')

-- THÊM 2 CHỨC NĂNG BÊN TRÊN VÀO MENU MOBILE  CHO TÀI KHOẢN SA
--
--100135
-- 100134
INSERT INTO base.ROLE_VALUE([GUID],[ROLE_ID],[ROLE_TYPE_ID],[VALUE]) VALUES(NEWID(),100400,100009,100135)
INSERT INTO base.ROLE_VALUE([GUID],[ROLE_ID],[ROLE_TYPE_ID],[VALUE]) VALUES(NEWID(),100400,100009,100134)
