CREATE OR ALTER FUNCTION nlg.Proc_getGia_Loai
(@GIACTY INT,@TYPEID INT,@COC VARCHAR(20),@OVER_PLAN INT,@TYLECHINHPHAM_CUA_PHIEU FLOAT,@NOTE_HC VARCHAR(30))
RETURNS INT
AS
BEGIN
	DECLARE @GIA INT,@RATE_DOWN FLOAT, @RATE_UP FLOAT,
	@HESO_DOWN INT,@HESO_UP INT,@GIA_HANG_LOAI INT
	SELECT @RATE_DOWN = TYLE,@HESO_DOWN=HESO FROM nlg.CONFIG_TYLE WHERE [TYPE]='DOWN'
	SELECT @RATE_UP = TYLE,@HESO_UP=HESO FROM nlg.CONFIG_TYLE WHERE [TYPE]='UP'
	SELECT @GIA = @GIACTY
	-- NẾU @TYPEID = 0
	-- TỨC LÀ CHÍNH PHẨM
	-- THÌ 
	--NẾU KHÔNG PHẢI HÀNG NHẬP HẠ CẤP
	-- @NOTE_HC = '0' OR @NOTE_HC='H'
	IF(@NOTE_HC='0' OR @NOTE_HC='H')
		BEGIN
			IF(@TYPEID<=6)
			BEGIN
				-- NẾU NHẬP NGOÀI KẾ HOẠCH TRỪ TIỀN THEO QUI ĐINH (200.000)
				IF(@OVER_PLAN=1)
					SELECT @GIA =@GIACTY-200000
				--NẾU NHÀ CUNG CÁP KHÔNG CÓ CHỨNG CHỈ COC
				-- THÌ BỊ TRỪ 70K
				IF(@COC ='N')
					SELECT @GIA =@GIACTY-70000
				--- NẾU TỶ LỆ CHÍNH PHẨM CỦA PHIẾU  TRONG KHOẢN ĐỊNH MỨC
				-- THÌ TRỪ THEO ĐỊNH MỨC
				IF @TYLECHINHPHAM_CUA_PHIEU <@RATE_DOWN
					BEGIN
						DECLARE @NumPercenDiff as int,@SOTIENTRU AS INT
						SELECT @NumPercenDiff = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR(30),@TYLECHINHPHAM_CUA_PHIEU*100),0,3)) - ROUND(@RATE_DOWN*100,0)
						SELECT @SOTIENTRU = @NumPercenDiff*@HESO_DOWN
						--@SOTIENTRU LÀ SỐ ÂM  => +
						SELECT @GIA = @GIA + @SOTIENTRU
					END
			END
		END

		RETURN @GIA
END
