CREATE OR ALTER FUNCTION nlg.Func_Tinh_ty_le_chinh_pham(@SOPHIEU_ID INT)
RETURNS FLOAT
AS
BEGIN
	-- TỶ LỆ CHÍNH PHẨM CỦA CẢ LÔ HÀNG 
	-- ĐƯỢC TÍNH BẰNG CÔNG THỨC
	-- TỔNG KHỐI LƯỢNG QC CỦA CHÍNH PHẨM / TỔNG KHỐI LƯỢNG KHO
	DECLARE @TONGKL_QC FLOAT,@LOOP_COUNTER INT,@MAX_ID INT,@MIN_ID INT,@TONG_KLKHO FLOAT,@TYLE FLOAT
	SELECT @MAX_ID=MAX(ID),@MIN_ID=MIN(ID) FROM nlg.PHIEUNHAPKHO_DT WHERE SOPHIEU_ID=@SOPHIEU_ID AND DEL_FLAG='N' AND DELAI='N'
	SELECT @LOOP_COUNTER = @MIN_ID
	IF @MAX_ID=@MIN_ID
		SELECT @TONGKL_QC = ROUND(ROUND(CAST(PT.SLMAU*PT.SOTHANHBO-(SELECT SUM(SL) FROM nlg.HACAP WHERE DEL_FLAG='N' AND DETAIL_ID=PT.ID) AS float)/CAST(PT.SLMAU*PT.SOTHANHBO AS FLOAT),4)*ROUND((PT.SOTHANHBO*PT.SOBO*QC.VOLUMN),4),4),
		@TONG_KLKHO= ROUND((PT.SOTHANHBO*PT.SOBO*QC.VOLUMN),4)
		FROM NLG.PHIEUNHAPKHO_DT AS PT
		INNER JOIN  NLG.QUICACH AS QC ON QC.ID = PT.ID_QUICACH
		WHERE PT.ID = @MAX_ID
	ELSE
	BEGIN
		WHILE(@LOOP_COUNTER IS NOT NULL AND @LOOP_COUNTER<@MAX_ID)
		BEGIN
			DECLARE @KLQC FLOAT,@KLKHO FLOAT
			SELECT @KLQC = ROUND(ROUND(CAST(PT.SLMAU*PT.SOTHANHBO-(SELECT SUM(SL) FROM nlg.HACAP WHERE DEL_FLAG='N' AND DETAIL_ID=PT.ID) AS float)/CAST(PT.SLMAU*PT.SOTHANHBO AS FLOAT),4)*ROUND((PT.SOTHANHBO*PT.SOBO*QC.VOLUMN),4),4),
			@KLKHO= ROUND((PT.SOTHANHBO*PT.SOBO*QC.VOLUMN),4)
			FROM NLG.PHIEUNHAPKHO_DT AS PT
			INNER JOIN  NLG.QUICACH AS QC ON QC.ID = PT.ID_QUICACH
			WHERE PT.ID = @LOOP_COUNTER
			SELECT @TONGKL_QC=@TONGKL_QC+@KLQC,@TONG_KLKHO = @TONG_KLKHO+@KLKHO
		
			SELECT @LOOP_COUNTER = MIN(ID)  FROM NLG.PHIEUNHAPKHO_DT WHERE ID>@LOOP_COUNTER
		END
	END
	SELECT @TYLE = ROUND(@TONGKL_QC/@TONG_KLKHO,4)
	RETURN @TYLE
END


--SELECT 
--ROUND(CAST(PT.SLMAU*PT.SOTHANHBO-(SELECT SUM(SL) FROM nlg.HACAP WHERE DEL_FLAG='N' AND DETAIL_ID=PT.ID) AS float)/CAST(PT.SLMAU*PT.SOTHANHBO AS FLOAT),4) AS [TYLE],
--ROUND(ROUND(CAST(PT.SLMAU*PT.SOTHANHBO-(SELECT SUM(SL) FROM nlg.HACAP WHERE DEL_FLAG='N' AND DETAIL_ID=PT.ID) AS float)/CAST(PT.SLMAU*PT.SOTHANHBO AS FLOAT),4)*ROUND((PT.SOTHANHBO*PT.SOBO*QC.VOLUMN),4),4) AS [KLQC],
--SUM(ROUND(ROUND(CAST(PT.SLMAU*PT.SOTHANHBO-(SELECT SUM(SL) FROM nlg.HACAP WHERE DEL_FLAG='N' AND DETAIL_ID=PT.ID) AS float)/CAST(PT.SLMAU*PT.SOTHANHBO AS FLOAT),4)*ROUND((PT.SOTHANHBO*PT.SOBO*QC.VOLUMN),4),4)) AS [KLQC]
--FROM nlg.PHIEUNHAPKHO_DT AS PT 
--INNER JOIN NLG.QUICACH AS QC ON QC.ID = PT.ID_QUICACH
--WHERE PT.SOPHIEU_ID =103034 AND PT.DEL_FLAG='N' AND PT.DELAI='N'


--SELECT  nlg.Func_Tinh_ty_le_chinh_pham(103034)

--SELECT * FROM nlg.PHIEUNHAPKHO WHERE [GUID]='EE92BFB3-7560-4F24-A540-4D52A9A7112C'