CREATE OR ALTER FUNCTION nlg.Func_get_MaSP
(@ID_QUICACH INT,@TYPE VARCHAR(30),@ID INT,@VUNG VARCHAR(30))
--@@ID_QUICACH : ID CỦA QUI CÁCH (1000001)
-- @TYPE : LOẠI (HACAP,CHINHPHAM)
--@ID : ID CỦA HẠ CẤP , HOẶC CHÍNH PHẨM
RETURNS VARCHAR(300)
AS
BEGIN

	DECLARE @MASP VARCHAR(300),@MA_QUICACH VARCHAR(30),@TYPE_ID INT,@LOAI VARCHAR(30),@NUM_RECORD_FOUND INT
	IF @TYPE='HC'
		SELECT @TYPE_ID = TYPEID FROM nlg.HACAP WHERE ID=@ID
	ELSE
		SELECT @TYPE_ID = 0

	SELECT @MA_QUICACH = CODE FROM nlg.QUICACH WHERE ID =@ID_QUICACH
	--IF @VUNG='QT'
	--	SELECT @MA_QUICACH='QT'+@MA_QUICACH
	

	SELECT @LOAI=''
	
	IF @VUNG='QT'
		SELECT @NUM_RECORD_FOUND = COUNT(*) FROM NLG.NLGO WHERE MANVLKHO=@MA_QUICACH AND LEFT(MANVL,2)='QT'
	ELSE
		SELECT @NUM_RECORD_FOUND = COUNT(*) FROM NLG.NLGO WHERE MANVLKHO=@MA_QUICACH AND LEFT(MANVL,2)<>'QT'
	--NẾU CÓ NHIỀU HƠN 1 BẢN GHI
	-- => QUI CÁCH GIÁ CÓ LOẠI 1 VÀ LOẠI 2
	IF(@NUM_RECORD_FOUND>1)
		BEGIN
			--NẾU LÀ CHÍNH PHẨM , HOẶC CHÍNH PHẨM B
			-- THÌ LÀ LOẠI L1
			IF @TYPE_ID <2
				SELECT @LOAI ='l1'
			ELSE
				--NGƯỢC LẠI 
				SELECT @LOAI = 'l2'
		END
	IF(@VUNG='QT')
		SELECT TOP 1 @MASP = MANVL FROM NLG.NLGO WHERE MANVLKHO=@MA_QUICACH AND LEFT(MANVL,2)='QT' AND MANVL=@MA_QUICACH+@LOAI
	ELSE
		SELECT  TOP 1 @MASP = MANVL FROM NLG.NLGO WHERE MANVLKHO=@MA_QUICACH AND LEFT(MANVL,2)<>'QT' AND MANVL=@MA_QUICACH+@LOAI
	RETURN @MASP
END