CREATE OR ALTER FUNCTION nlg.Func_validate_nhap_kho(
	@SOPHIEU_ID INT,@ID_QUICACH INT,@SOTHANH INT, @SOTHANHBO INT
)
RETURNS INT
AS
BEGIN
	DECLARE @NGAY_NHAP_KHO DATETIME,@MANCC INT,
	@MAKHO INT,@KHOI_LUONG_NHAP FLOAT, @KH_NCC FLOAT,@KH_TONG FLOAT,@GROUP_QC_ID INT,
	@TH_NCC  FLOAT,@RESULT BIT,@MESSAGE NVARCHAR(300),@TH_THANG FLOAT
	SELECT @GROUP_QC_ID = GROUP_ID  FROM nlg.QUICACH WHERE ID = @ID_QUICACH
	SELECT @NGAY_NHAP_KHO = RECEIPT_DATE,@MANCC=MANCC,@MAKHO=MAKHO FROM nlg.PHIEUNHAPKHO WHERE ID = @SOPHIEU_ID
	SELECT @KH_NCC=nlg.Func_lay_kh_ncc_theo_nhom_qui_cach(@SOPHIEU_ID,@GROUP_QC_ID)
	-- KIỂM TRA KẾ HOẠCH NHÀ CUNG CẤP
	--SELECT @KH_TONG = nlg.Func_lay_kh_tong_theo_qc(@SOPHIEU_ID,@GROUP_QC_ID)
	SELECT @TH_NCC = nlg.Func_lay_thu_hien_theo_ncc(@MANCC,@NGAY_NHAP_KHO,@ID_QUICACH)
	--SELECT @TH_THANG = nlg.Func_lay_thu_hien_thang_theo_qui_cach(@MANCC,@NGAY_NHAP_KHO,@ID_QUICACH)
	SELECT @KHOI_LUONG_NHAP = ROUND(PT.SOBO*PT.SOTHANHBO*QC.VOLUMN,4) FROM nlg.PHIEUNHAPKHO_DT  AS PT
	JOIN nlg.QUICACH AS QC ON QC.ID = PT.ID_QUICACH


	IF @KH_NCC IS NULL
		SELECT @KH_NCC=0
	IF @TH_NCC IS NULL
		SELECT @TH_NCC = 0



	--2020-03-25 COMFIRM VỚI MR HIỆN
	-- CHO PHÉP NHẬP VƯỢT KẾ HOẠCH THÁNG


	-- NẾU THỰC HIỆN THÁNG CỦA NCC + KHỐI LƯỢNG NHẬP  >= KẾ HOẠCH CỦA NHÀ CUNG CẤP
	-- NHẬP NGOÀI KẾ HOẠCH
	IF(@KHOI_LUONG_NHAP+@TH_NCC<=@KH_NCC)
		RETURN 0
	RETURN 1



	---- NẾU THỰC HIỆN THÁNG + KHỐI LƯỢNG NHẬP  >= KẾ HOẠCH THÁNG
	--IF(@KHOI_LUONG_NHAP+@TH_THANG>=@KH_TONG)
	--	BEGIN
	--		SELECT @RESULT=0,@MESSAGE=N'KHÔNG THỂ VƯỢT KẾ HOẠCH THÁNG !'
	--	END
	--ELSE
	--	BEGIN
			
	--	END


	-- NẾU KHỐI LƯỢNG NHẬP + KHỐI LƯỢNG ĐÃ THỰC HIỆN TRONG THÁNG >  KẾ HOẠCH TỔNG
	-- KHÔNG CHO PHÉP NHẬP
	--IF @TH_NCC+
	-- NẾU KHỐI LƯỢNG NHẬP VÀO VƯỢT KẾ HOẠCH NHÀ CUNG CẤP BÁO FAIL VÀ SỐ LƯỢNG TỐI ĐA CÓ THỂ NHẬP
END





--select nlg.Func_validate_nhap_kho(
--103034,100007,14,14
--)

--select [nlg].[Func_lay_thu_hien_thang_theo_qui_cach](100001,'2020-04-03 00:00:00.000',100005)


--select * from nlg.GROUP_QUICACH 

--select * from nlg.QUICACH where id=100007
--select * from nlg.PHIEUNHAPKHO WHERE ID=103034