CREATE OR ALTER FUNCTION nlg.Func_getGia_Cong_ty(
	@NGAY_NHAP_KHO DATETIME,@MASP VARCHAR(50),@TYPEID INT,@NOTE_HC VARCHAR(30),@TYPE_CHINHPHAM_CUA_BB FLOAT
)
RETURNS INT
AS
BEGIN
	DECLARE @GIA INT
	IF (@NOTE_HC='0' OR @NOTE_HC='H')
		BEGIN
			IF @TYPEID<=6
				BEGIN
					SELECT TOP 1 @GIA = COST FROM nlg.BANGGIANVL WHERE APPLY_DATE<=@NGAY_NHAP_KHO AND MASP=@MASP ORDER BY APPLY_DATE DESC
					
				END
			ELSE
				SELECT @GIA = COST FROM NLG.CF_GIA_LOAI WHERE [TYPE]=@TYPEID
		END
		ELSE
			SELECT @GIA = COST FROM NLG.CF_GIA_LOAI WHERE [CODE]=@NOTE_HC
	IF @GIA IS NULL
		SELECT @GIA =0
	RETURN @GIA
END