CREATE OR ALTER PROC Proc_removePallet
@PALLET_CODE VARCHAR(20),
@ACCOUNT_ID INT,
@ERROR INT OUTPUT
AS
BEGIN

SET XACT_ABORT ON
BEGIN TRANSACTION

DELETE MIP
FROM prod.[MATERIALS_IN_PACKAGE] MIP
LEFT JOIN prod.[ITEM_IN_PACKAGE] IIP ON IIP.ID = MIP.ITEM_IN_PACKAGE_ID
LEFT JOIN prod.[PACKAGE] P ON P.ID = IIP.PACKAGE_ID
LEFT JOIN prod.[STEP_OF_PALLET] SOP ON SOP.ID = P.STEP_OF_PALLET_ID
LEFT JOIN prod.[PALLET] PL ON PL.ID = SOP.PALLET_ID
WHERE PL.CODE = @PALLET_CODE

DELETE IIP
FROM prod.[ITEM_IN_PACKAGE] IIP
LEFT JOIN prod.[PACKAGE] P ON P.ID = IIP.PACKAGE_ID
LEFT JOIN prod.[STEP_OF_PALLET] SOP ON SOP.ID = P.STEP_OF_PALLET_ID
LEFT JOIN prod.[PALLET] PL ON PL.ID = SOP.PALLET_ID
WHERE PL.CODE = @PALLET_CODE

DELETE P
FROM prod.[PACKAGE] P
LEFT JOIN prod.[STEP_OF_PALLET] SOP ON SOP.ID = P.STEP_OF_PALLET_ID
LEFT JOIN prod.[PALLET] PL ON PL.ID = SOP.PALLET_ID
WHERE PL.CODE = @PALLET_CODE

DELETE SOP
FROM prod.[STEP_OF_PALLET] SOP
LEFT JOIN prod.[PALLET] PL ON PL.ID = SOP.PALLET_ID
WHERE PL.CODE = @PALLET_CODE

DELETE IIP
FROM prod.[ITEM_IN_PALLET] IIP
LEFT JOIN prod.[PALLET] PL ON PL.ID = IIP.PALLET_ID
WHERE PL.CODE = @PALLET_CODE


DELETE FROM prod.[PALLET]
WHERE CODE = @PALLET_CODE

COMMIT
END