
/*
DECLARE @RC int
DECLARE @PALLET_ID int

-- TODO: Set parameter values here.

EXECUTE [prod].[Proc_getStepNextId] 
   @PALLET_ID = 100128
GO

*/

CREATE OR ALTER PROC Proc_getStepNextId
@PALLET_ID INT
AS
BEGIN

DECLARE @STEP_NOW INT
DECLARE @ORDER INT

SELECT TOP(1) @STEP_NOW = SOP.STEP_NEXT_ID
FROM prod.[STEP_OF_PALLET] SOP
WHERE SOP.PALLET_ID = @PALLET_ID
ORDER BY ID DESC


SELECT @ORDER = R.[ORDER]
FROM prod.[ITEM_IN_PALLET] IIP
LEFT JOIN prod.[ROUTING] R ON R.ITEM_ID = IIP.ITEM_ID
WHERE IIP.PALLET_ID = @PALLET_ID
AND R.STEP_ID = @STEP_NOW

IF @ORDER IS NULL
BEGIN
    SET @ORDER = 0
END

SET @ORDER = @ORDER + 1

IF EXISTS ( SELECT R.STEP_ID
            FROM prod.[ITEM_IN_PALLET] IIP
            LEFT JOIN prod.[ROUTING] R ON R.ITEM_ID = IIP.ITEM_ID
            WHERE IIP.PALLET_ID = @PALLET_ID
            AND R.[ORDER] = @ORDER
        )
    BEGIN
        SELECT R.STEP_ID
        FROM prod.[ITEM_IN_PALLET] IIP
        LEFT JOIN prod.[ROUTING] R ON R.ITEM_ID = IIP.ITEM_ID
        WHERE IIP.PALLET_ID = @PALLET_ID
        AND R.[ORDER] = @ORDER
    END
ELSE
    BEGIN
        SELECT RN.DEPARTMENT_ID STEP_ID
        FROM prod.PALLET PL
        LEFT JOIN prod.PRODUCTION_ORDERS PO ON PO.ID = PL.PRODUCTION_ORDERS_ID
        LEFT JOIN prod.STEP_OF_PALLET SOP ON SOP.PALLET_ID = PL.ID
        LEFT JOIN prod.ROUTINGS RC ON RC.NAME = PO.ROUTING_NAME AND RC.DEPARTMENT_ID = SOP.STEP_NEXT_ID
        LEFT JOIN prod.ROUTINGS RN ON RN.NAME = RC.NAME AND RN.[ORDER] = RC.[ORDER] + 1
        WHERE PL.ID = @PALLET_ID
        ORDER BY SOP.ID DESC
    END
END