CREATE OR ALTER PROC nlg.Proc_Them_Ma_Nhap_Kho
@SOPHIEU_ID INT,@ID_QUICACH INT,@SOTHANH INT, @SOTHANHBO INT,@NOTE  NVARCHAR(300),@DELAI VARCHAR(10),@TYPE VARCHAR(30)
AS
BEGIN
	DECLARE @VALIDATE_DATA BIT,@RESULT AS BIT,@MESSAGE AS NVARCHAR(300)
	SELECT @VALIDATE_DATA = nlg.Func_validate_nhap_kho(@SOPHIEU_ID,@ID_QUICACH,@SOTHANH,@SOTHANHBO)

	
	BEGIN TRY
		INSERT INTO nlg.PHIEUNHAPKHO_DT([SOPHIEU_ID],[ID_QUICACH],[SOBO],[SOTHANHBO],[NOTE],CREATE_DATE,[DELAI],[OVER_PLAN],[NOTE_HC],[DEL_FLAG])
		VALUES(@SOPHIEU_ID,@ID_QUICACH,@SOTHANH,@SOTHANHBO,@NOTE,GETDATE(),@DELAI,@VALIDATE_DATA,@TYPE,'N')
		SELECT @RESULT=1,@MESSAGE='SUCCESS'	
	END TRY
	BEGIN CATCH
		SELECT @RESULT =0,@MESSAGE = ERROR_MESSAGE()
	END CATCH
	SELECT @RESULT AS [RESULT],@MESSAGE AS [MESSAGE]

END
