CREATE OR ALTER PROC nlg.Proc_get_bb_tt
@SOPHIEU_ID INT
AS
BEGIN
	select PT.ID,NULL AS PARENT_ID,N'Chính phẩm' AS [PHANLOAI],QC.[DAY],QC.RONG,QC.DAI,PT.SOBO*PT.SOTHANHBO AS [TONGSOTHANH],
PT.SOTHANHBO*PT.SLMAU AS [SL_MAU],
PT.SLMAU*PT.SOTHANHBO-(SELECT SUM(SL) FROM nlg.HACAP WHERE DEL_FLAG='N' AND DETAIL_ID=PT.ID) AS [GOOD_QTY],
ROUND(CAST(PT.SLMAU*PT.SOTHANHBO-(SELECT SUM(SL) FROM nlg.HACAP WHERE DEL_FLAG='N' AND DETAIL_ID=PT.ID) AS float)/CAST(PT.SLMAU*PT.SOTHANHBO AS FLOAT),4) AS [TYLE],
ROUND(ROUND(CAST(PT.SLMAU*PT.SOTHANHBO-(SELECT SUM(SL) FROM nlg.HACAP WHERE DEL_FLAG='N' AND DETAIL_ID=PT.ID) AS float)/CAST(PT.SLMAU*PT.SOTHANHBO AS FLOAT),4)*ROUND((PT.SOTHANHBO*PT.SOBO*QC.VOLUMN),4),4) AS [KLQC],
ROUND((PT.SOTHANHBO*PT.SOBO*QC.VOLUMN),4) AS [KLKHO],PT.NOTE,PT.NOTE_HC,
nlg.Func_get_MaSP(PT.ID_QUICACH,'CP',PT.ID,PR.VUNG) as [MA_SP],
nlg.Func_getGia_Cong_ty(PN.RECEIPT_DATE,nlg.Func_get_MaSP(PT.ID_QUICACH,'CP',PT.ID,PR.VUNG),0,PT.NOTE_HC) AS [GIA_CTY],
nlg.Proc_getGia_Loai(nlg.Func_getGia_Cong_ty(PN.RECEIPT_DATE,nlg.Func_get_MaSP(PT.ID_QUICACH,'CP',PT.ID,PR.VUNG),0,PT.NOTE_HC),
0,PR.COC,PT.OVER_PLAN,
nlg.Func_Tinh_ty_le_chinh_pham(@SOPHIEU_ID),
PT.NOTE_HC
) AS [GIA_LOAI]
from nlg.PHIEUNHAPKHO_DT  AS PT
INNER JOIN nlg.PHIEUNHAPKHO AS PN ON PN.ID = PT.SOPHIEU_ID
INNER JOIN NLG.PROVIDERS AS PR ON PR.ID = PN.MANCC
INNER JOIN NLG.QUICACH AS QC ON QC.ID = PT.ID_QUICACH
WHERE PT.DEL_FLAG='N' AND PT.DELAI='N' AND PN.ID=@SOPHIEU_ID
UNION ALL
SELECT HC.ID,HC.DETAIL_ID AS PARENT_ID, TY.TYPENAME,QC.[DAY],QC.RONG,QC.DAI,NULL AS [TONGSOTHANH],
NULL AS [SL_MAU],HC.SL AS [GOOD_QTY],
ROUND(CAST(HC.SL AS FLOAT)/CAST(PT.SLMAU*PT.SOTHANHBO AS FLOAT),4) AS [TYLE],
ROUND(QC.VOLUMN*PT.SOTHANHBO*PT.SOBO,4) AS KLKHO,
NULL AS [KLKHO],HC.NOTE,NULL AS [NOTE_HC],
nlg.Func_get_MaSP(HC.QUICACH_ID,'HC',HC.ID,PR.VUNG) as [MA_SP],
nlg.Func_getGia_Cong_ty(PN.RECEIPT_DATE,nlg.Func_get_MaSP(HC.QUICACH_ID,'HC',HC.ID,PR.VUNG),HC.TYPEID,'H') AS [GIA_CTY],
nlg.Proc_getGia_Loai(nlg.Func_getGia_Cong_ty(PN.RECEIPT_DATE,nlg.Func_get_MaSP(HC.QUICACH_ID,'HC',HC.ID,PR.VUNG),HC.TYPEID,'H'),
HC.TYPEID,PR.COC,PT.OVER_PLAN,nlg.Func_Tinh_ty_le_chinh_pham(@SOPHIEU_ID),'H') AS [GIA_LOAI]
FROM NLG.HACAP AS HC
INNER JOIN nlg.PHIEUNHAPKHO_DT AS PT ON PT.ID = HC.DETAIL_ID
INNER JOIN NLG.PHIEUNHAPKHO AS PN ON PN.ID = PT.SOPHIEU_ID
INNER JOIN nlg.PROVIDERS AS PR ON PN.MANCC = PR.ID
INNER JOIN NLG.QUICACH AS QC ON HC.QUICACH_ID = QC.ID
INNER JOIN NLG.TYPE_HACAP AS TY ON TY.ID = HC.TYPEID
WHERE PN.ID=@SOPHIEU_ID AND HC.DEL_FLAG='N'


END