CREATE OR ALTER PROC nlg.Proc_View_bb
@GUID VARCHAR(100)
as
BEGIN
	DECLARE @SOPHIEU_ID INT
	SELECT TOP 1 @SOPHIEU_ID = ID FROM nlg.PHIEUNHAPKHO WHERE [GUID]=@GUID ORDER BY ID DESC
	select PT.ID,NULL AS PARENT_ID,N'Chính phẩm' AS [PHANLOAI],QC.[DAY],QC.RONG,QC.DAI,PT.SOBO*PT.SOTHANHBO AS [TONGSOTHANH],
	PT.SOTHANHBO*PT.SLMAU AS [SL_MAU],
	PT.SLMAU*PT.SOTHANHBO-(SELECT SUM(SL) FROM nlg.HACAP WHERE DEL_FLAG='N' AND DETAIL_ID=PT.ID) AS [GOOD_QTY],
	ROUND(CAST(PT.SLMAU*PT.SOTHANHBO-(SELECT SUM(SL) FROM nlg.HACAP WHERE DEL_FLAG='N' AND DETAIL_ID=PT.ID) AS float)/CAST(PT.SLMAU*PT.SOTHANHBO AS FLOAT),4) AS [TYLE],
	ROUND(ROUND(CAST(PT.SLMAU*PT.SOTHANHBO-(SELECT SUM(SL) FROM nlg.HACAP WHERE DEL_FLAG='N' AND DETAIL_ID=PT.ID) AS float)/CAST(PT.SLMAU*PT.SOTHANHBO AS FLOAT),4)*ROUND((PT.SOTHANHBO*PT.SOBO*QC.VOLUMN),4),4) AS [KLQC],
	ROUND((PT.SOTHANHBO*PT.SOBO*QC.VOLUMN),4) AS [KLKHO],PT.NOTE,PT.NOTE_HC,
	PT.DONGIA AS [GIA_CTY],PT.DONGIA_LOAI AS [GIA_LOAI],PT.DONGIATB
	from nlg.PHIEUNHAPKHO_DT  AS PT
	INNER JOIN nlg.PHIEUNHAPKHO AS PN ON PN.ID = PT.SOPHIEU_ID
	INNER JOIN NLG.PROVIDERS AS PR ON PR.ID = PN.MANCC
	INNER JOIN NLG.QUICACH AS QC ON QC.ID = PT.ID_QUICACH
	WHERE PT.DEL_FLAG='N' AND PT.DELAI='N' AND PN.ID=@SOPHIEU_ID
	UNION ALL
	SELECT HC.ID,HC.DETAIL_ID AS PARENT_ID, TY.TYPENAME,QC.[DAY],QC.RONG,QC.DAI,NULL AS [TONGSOTHANH],
	NULL AS [SL_MAU],HC.SL AS [GOOD_QTY],
	ROUND(CAST(HC.SL AS FLOAT)/CAST(PT.SLMAU*PT.SOTHANHBO AS FLOAT),4) AS [TYLE],
	ROUND(QC.VOLUMN*PT.SOTHANHBO*PT.SOBO,4) AS KLKHO,
	NULL AS [KLKHO],HC.NOTE,NULL AS [NOTE_HC],HC.DONGIA_CTY AS [GIA_CTY],
	HC.DONGIA_LOAI AS [GIA_LOAI],NULL AS [DONGIATB]
	FROM NLG.HACAP AS HC
	INNER JOIN nlg.PHIEUNHAPKHO_DT AS PT ON PT.ID = HC.DETAIL_ID
	INNER JOIN NLG.PHIEUNHAPKHO AS PN ON PN.ID = PT.SOPHIEU_ID
	INNER JOIN nlg.PROVIDERS AS PR ON PN.MANCC = PR.ID
	INNER JOIN NLG.QUICACH AS QC ON HC.QUICACH_ID = QC.ID
	INNER JOIN NLG.TYPE_HACAP AS TY ON TY.ID = HC.TYPEID
	WHERE PN.ID=@SOPHIEU_ID AND HC.DEL_FLAG='N'
END