CREATE OR ALTER PROC nlg.Proc_delai_1_phan
@ID_OLD INT,@SOBO_DELAI INT,@NOTE NVARCHAR(300)
AS
BEGIN
	 DECLARE @SOPHIEU_ID INT,@ID_QUICACH INT,@SOTHANHBO INT,@NOTE_HC VARCHAR(30),@RESULT AS BIT,@MESSAGE AS NVARCHAR(499)
	 SELECT @SOPHIEU_ID = SOPHIEU_ID,@ID_QUICACH=ID_QUICACH,@SOTHANHBO=SOTHANHBO,@NOTE_HC=NOTE_HC FROM nlg.PHIEUNHAPKHO_DT WHERE ID=@ID_OLD
		BEGIN TRY
			INSERT INTO nlg.PHIEUNHAPKHO_DT([SOPHIEU_ID],[ID_QUICACH],SOBO,SOTHANHBO,NOTE,CREATE_DATE,DEL_FLAG,DELAI,NOTE_HC)
			values(@SOPHIEU_ID,@ID_QUICACH,@SOBO_DELAI,@SOTHANHBO,@NOTE,GETDATE(),'N','Y',@NOTE_HC)
			SELECT @RESULT =1,@MESSAGE='SUCCESS'
		END TRY
		BEGIN CATCH
		SELECT @RESULT=0,@MESSAGE=ERROR_MESSAGE()
		END CATCH

		SELECT @RESULT AS RESULT,@MESSAGE AS [MESSAGE]
END
