CREATE OR ALTER PROC nlg.Proc_Sua_Nha_Cung_Cap
@ID INT,@STAFF INT,@COC NCHAR(10),@COHD NCHAR(10)
AS
BEGIN
	DECLARE @RESULT BIT,@MESSGAE NVARCHAR(300)
	BEGIN TRY
		UPDATE nlg.PROVIDERS SET STAFF=@STAFF,COC =@COC,COHD=@COHD WHERE ID =@ID
		SELECT @RESULT =1,@MESSGAE=N'Thành công !'	
	END TRY
	BEGIN CATCH
		SELECT @RESULT =0,@MESSGAE= ERROR_MESSAGE()
	END CATCH
	SELECT @RESULT AS [RESULT],@MESSGAE AS [MESSAGE]
END