CREATE OR ALTER PROC nlg.Proc_Create_Provider
@CODE NVARCHAR(200),@NAME NVARCHAR(300),@ADDRESS NVARCHAR(300),@STAFF INT,
@VUNG NVARCHAR(20),@VUNG2 NVARCHAR(30),@COC NCHAR(10),@COHD NCHAR(10),@UID INT
AS
BEGIN
	DECLARE @RESULT BIT,@MESSGAE NVARCHAR(300)
	
	BEGIN TRY
		INSERT INTO nlg.PROVIDERS([CODE],[NAME],[ADDRESS],[COC],[STAFF],[COHD],[VUNG],
		[VUNG2],[INSERT_BY],[INSERT_TIME])
		VALUES(@CODE,@NAME,@ADDRESS,@COC,@STAFF,@COHD,@VUNG,@VUNG2,@UID,GETDATE())
		SELECT @RESULT =1,@MESSGAE=N'Thành công !'	
	END TRY
	BEGIN CATCH
		SELECT @RESULT =0,@MESSGAE= ERROR_MESSAGE()
	END CATCH
	SELECT @RESULT AS [RESULT],@MESSGAE AS [MESSAGE]
END