CREATE OR ALTER PROC nlg.Proc_View_Ha_Cap_Theo_So_Phieu
@GUID VARCHAR(400)
AS
BEGIN
	DECLARE @SOPHIEU_ID INT
	SELECT TOP 1 @SOPHIEU_ID = ID FROM nlg.PHIEUNHAPKHO WHERE [GUID] =@GUID ORDER BY ID DESC
	SELECT PT.ID,NULL AS PARENT_ID,ID_QUICACH,SOBO,PT.SOTHANHBO*pt.SOBO AS [SOTHANHGIAO],PT.SLMAU,PT.GOOD_QTY,PT.GOOD_QTY/PT.SLMAU AS TYLE,
	ROUND(PT.SOBO*PT.SOTHANHBO*QC.VOLUMN,4) AS [KHOILUONG],PT.NOTE,N'Chính phẩm' as [TYPE],QC.CODE AS [QUICACH_CODE],
	qc.DAY,QC.RONG,QC.DAI
	FROM NLG.PHIEUNHAPKHO_DT AS PT
	JOIN NLG.QUICACH AS  QC ON QC.ID = PT.ID_QUICACH
	WHERE SOPHIEU_ID=@SOPHIEU_ID
	UNION ALL
	SELECT HC.ID,HC.DETAIL_ID AS [PARENT_ID],HC.QUICACH_ID AS [ID_QUICACH],NULL AS SOBO,NULL AS [SOTHANHGIAO],NULL AS SLMAU,HC.SL AS [GOOD_QTY],
	HC.SL/PT.SLMAU AS [TYLE],ROUND(QC.VOLUMN*HC.SL,4) AS [KHOILUONG],HC.NOTE,TP.[TYPENAME] AS [TYPE],QC.CODE AS [QUICACH_CODE],
	qc.DAY,QC.RONG,QC.DAI
	FROM NLG.HACAP AS HC
	JOIN NLG.PHIEUNHAPKHO_DT AS PT ON PT.ID = HC.DETAIL_ID
	JOIN nlg.QUICACH AS QC ON QC.ID = HC.QUICACH_ID
	JOIN NLG.TYPE_HACAP AS TP ON TP.ID = HC.[TYPEID]
	WHERE PT.SOPHIEU_ID =@SOPHIEU_ID

END
--select * from WoodslandNLG.dbo.TINHTIEN