CREATE OR ALTER PROC Proc_getStepState
AS
BEGIN



-- đến kho nhưng chưa nhận
SELECT * FROM View_inNotVerify
CREATE OR ALTER VIEW View_inNotVerify
AS
SELECT SOP.STEP_NEXT_ID AS DENKHO,
PL.ID PALLET_ID,
--PL.CODE PALLET_CODE,
P.ID PACKAGE_ID,
P.CREATE_BY,
P.CREATE_DATE,
P.VERIFY_BY,
P.VERIFY_DATE
FROM dbo.[STEP_OF_PALLET] SOP
LEFT JOIN dbo.[PACKAGE] P ON P.STEP_OF_PALLET_ID = SOP.ID AND P.DESTINATION_ID = SOP.STEP_NEXT_ID
LEFT JOIN dbo.[PALLET] PL ON PL.ID = SOP.PALLET_ID
WHERE P.VERIFY_BY IS NULL


-- đã nhận nhưng chưa xuất
SELECT SOP.STEP_NEXT_ID AS DENKHO,
PL.ID PALLET_ID,
--PL.CODE PALLET_CODE,
P.ID PACKAGE_ID,
P.CREATE_BY,
P.CREATE_DATE,
P.VERIFY_BY,
P.VERIFY_DATE,
SOPOUT.STEP_ID,
SOPOUT.STEP_NEXT_ID
FROM dbo.[STEP_OF_PALLET] SOP
LEFT JOIN dbo.[PACKAGE] P ON P.STEP_OF_PALLET_ID = SOP.ID AND P.DESTINATION_ID = SOP.STEP_NEXT_ID
LEFT JOIN dbo.[PALLET] PL ON PL.ID = SOP.PALLET_ID
LEFT JOIN dbo.[STEP_OF_PALLET] SOPOUT ON SOPOUT.PALLET_ID = SOP.PALLET_ID AND SOPOUT.STEP_ID = SOP.STEP_NEXT_ID
WHERE P.VERIFY_BY IS NOT NULL -- đã nhận
AND SOPOUT.ID IS NULL -- nhưng chưa xuất
ORDER BY SOP.STEP_NEXT_ID ASC




-- đã xuất nhưng chưa nhận
SELECT SOP.STEP_ID AS RAKHO,
PL.ID PALLET_ID,
--PL.CODE PALLET_CODE,
P.ID PACKAGE_ID,
P.CREATE_BY,
P.CREATE_DATE
FROM dbo.[STEP_OF_PALLET] SOP
LEFT JOIN dbo.[PACKAGE] P ON P.STEP_OF_PALLET_ID = SOP.ID AND P.DESTINATION_ID = SOP.STEP_NEXT_ID
LEFT JOIN dbo.[PALLET] PL ON PL.ID = SOP.PALLET_ID
WHERE P.VERIFY_BY IS NULL
ORDER BY SOP.STEP_NEXT_ID ASC



END