CREATE OR ALTER VIEW [dbo].[View_TON_QC]
AS
SELECT * 
FROM (
SELECT N.ID,N.[FROM],N.ITEM_ID, 
CASE 
WHEN N.IMPORT IS NULL AND X.EXPORT IS NULL THEN 0
WHEN N.IMPORT IS NULL AND X.EXPORT IS NOT NULL THEN X.EXPORT*(-1)
WHEN N.IMPORT IS NOT NULL AND X.EXPORT IS NULL THEN N.IMPORT
WHEN N.IMPORT IS NOT NULL AND X.EXPORT IS NOT NULL THEN N.IMPORT - X.EXPORT
ELSE N.IMPORT - X.EXPORT
END AS REMAIN
FROM
(
SELECT ID,[FROM],ITEM_ID,SUM(IMPORT) IMPORT
FROM View_NHAP_QC
--WHERE ID = 100025
GROUP BY ID,[FROM],ITEM_ID
) N LEFT JOIN
(
SELECT ID,ITEM_FROM_ID,ITEM_ID,SUM(EXPORT) EXPORT
FROM View_XUAT_QC
--WHERE ID = 100025
GROUP BY ID, ITEM_FROM_ID,ITEM_ID
) X ON N.ID = X.ID AND N.[FROM] = X.ITEM_FROM_ID AND N.ITEM_ID = X.ITEM_ID
) TON 
WHERE TON.REMAIN > 0