CREATE OR ALTER  VIEW [dbo].[View_NHAP_QC]
AS
SELECT 
D.ID,
D.[NAME],
GD.CODE,
P.SOURCE_ID AS [FROM],
IIP.ITEM_ID,
SUM(IIP.QUANTITY) IMPORT
FROM prod.PACKAGE P -- nhâp kho
LEFT JOIN prod.[ITEM_IN_PACKAGE] IIP ON IIP.PACKAGE_ID = P.ID
LEFT JOIN base.[DEPARTMENT] D ON D.ID = P.DESTINATION_ID
LEFT JOIN base.[GLOBAL_DATE] GD ON GD.YEAR = YEAR(P.CREATE_DATE) AND GD.MONTH = MONTH(P.CREATE_DATE) AND GD.DAY = DAY(P.CREATE_DATE)
--WHERE P.VERIFY_BY IS NOT NULL
GROUP BY D.ID,
D.[NAME],
GD.CODE,
P.SOURCE_ID,
IIP.ITEM_ID