CREATE OR ALTER  VIEW [dbo].[View_XUAT_QC]
AS
SELECT D.ID,
D.[NAME],
GD.CODE,
P.DESTINATION_ID AS [TO],
P.ITEM_FROM_ID,
IIP.ITEM_ID,
SUM(IIP.QUANTITY) EXPORT
FROM prod.[PACKAGE] P -- xuất hàng thành phẩm kho 
LEFT JOIN prod.[ITEM_IN_PACKAGE] IIP ON IIP.PACKAGE_ID = P.ID
LEFT JOIN base.[DEPARTMENT] D ON D.ID = P.SOURCE_ID
LEFT JOIN base.[GLOBAL_DATE] GD ON GD.YEAR = YEAR(P.CREATE_DATE) AND GD.MONTH = MONTH(P.CREATE_DATE) AND GD.DAY = DAY(P.CREATE_DATE)
--WHERE P.VERIFY_BY IS NOT NULL
GROUP BY D.ID,
D.[NAME],
GD.CODE,
P.DESTINATION_ID,
P.ITEM_FROM_ID,
IIP.ITEM_ID