
CREATE OR ALTER  VIEW [prod].[View_PalletInKilnBatch]
AS
SELECT KB.ID KILN_BATCH_ID,PL.ID,PL.CODE
FROM prod.[KILN_BATCH] KB
LEFT JOIN prod.[KILN] K ON K.ID = KB.KILN_ID
LEFT JOIN prod.[STEP_OF_PALLET] SOP ON SOP.KILN_BATCH_ID = KB.ID
LEFT JOIN prod.PALLET PL ON PL.ID = SOP.PALLET_ID
WHERE KB.TIME_OUT_REAL IS NULL
AND PL.ID IS NOT NULL