CREATE OR ALTER  VIEW [prod].[View_itemInPalletInKilnBatch]
AS
SELECT PL.ID, IIP.ITEM_ID,IIP.QUANTITY
FROM prod.[KILN_BATCH] KB
LEFT JOIN prod.[KILN] K ON K.ID = KB.KILN_ID
LEFT JOIN prod.[STEP_OF_PALLET] SOP ON SOP.KILN_BATCH_ID = KB.ID
LEFT JOIN prod.PALLET PL ON PL.ID = SOP.PALLET_ID
LEFT JOIN prod.[ITEM_IN_PALLET] IIP ON IIP.PALLET_ID = PL.ID
WHERE KB.TIME_OUT_REAL IS NULL
AND PL.ID IS NOT NULL