--SELECT * FROM prod.[View_kilnBatch]


CREATE OR ALTER  VIEW [prod].[View_kilnBatch]
AS
SELECT A.ID,
'' 'WEEK',
'' NUMBER,
CASE
	WHEN A.[WEEK] < 10 AND A.NUMBER < 10 THEN CONCAT (A.[YEAR],'.0',A.[WEEK],'.0',A.[NUMBER])
	WHEN A.[WEEK] < 10 AND A.NUMBER > 10 THEN CONCAT (A.[YEAR],'.0',A.[WEEK],'.',A.[NUMBER])
	WHEN A.[WEEK] > 10 AND A.NUMBER < 10 THEN CONCAT (A.[YEAR],'.',A.[WEEK],'.0',A.[NUMBER])
	WHEN A.[WEEK] > 10 AND A.NUMBER > 10 THEN CONCAT (A.[YEAR],'.',A.[WEEK],'.',A.[NUMBER])
	ELSE CONCAT (A.[YEAR],'.',A.[WEEK],'.',A.[NUMBER])
END AS 'YEAR',
A.KILN_ID,A.KILN_CODE,A.KILN_NAME,A.FACTORY_ID,A.TIME_OUT_TARGET,A.TIME_OUT,A.STEP_NEXT_ID,A.CREATE_BY,A.CREATE_DATE,A.[LENGTH],A.HEIGHT,A.VERIFY,A.VERIFY_BY,A.HUMIDITY,A.[STATE],A.[TYPE],A.[STATUS],SUM(A.MM3)* 10e-10 TOTAL_M3
FROM (
    SELECT KB.ID ID,
    KB.[YEAR],KB.[WEEK],KB.[NUMBER],
    K.ID KILN_ID,
    K.CODE KILN_CODE,
    K.NAME KILN_NAME,
    K.FACTORY_ID,
    KB.TIME_OUT_TARGET,
    KB.CREATE_DATE + KB.TIME_OUT_TARGET AS TIME_OUT,
    KB.STEP_NEXT_ID,
    KB.CREATE_BY,
    KB.CREATE_DATE,
    KB.[LENGTH],
    KB.HEIGHT,
    KB.VERIFY,
    KB.VERIFY_BY,
    KB.HUMIDITY,
    KB.[STATE],
	KB.[TYPE],
	KB.[STATUS],
    (((I.LENGTH * I.WIDTH * I.HEIGHT) * IIP.QUANTITY)) MM3
    FROM prod.[KILN_BATCH] KB
    LEFT JOIN prod.[KILN] K ON K.ID = KB.KILN_ID
    LEFT JOIN prod.STEP_OF_PALLET SOP ON SOP.KILN_BATCH_ID = KB.ID
    LEFT JOIN prod.PALLET PL ON PL.ID = SOP.PALLET_ID
    LEFT JOIN prod.ITEM_IN_PALLET IIP ON IIP.PALLET_ID = PL.ID
    LEFT JOIN base.ITEM I ON I.ID = IIP.ITEM_ID
    WHERE KB.TIME_OUT_REAL IS NULL
) A
GROUP BY 
A.ID,A.[YEAR],A.WEEK,A.NUMBER,A.KILN_ID,A.KILN_CODE,A.KILN_NAME,A.FACTORY_ID,A.TIME_OUT_TARGET,A.TIME_OUT,A.STEP_NEXT_ID,A.CREATE_BY,A.CREATE_DATE,A.[LENGTH],A.[HEIGHT],A.VERIFY,A.VERIFY_BY,A.HUMIDITY,A.[STATE],A.[TYPE],A.[STATUS]




