CREATE OR ALTER VIEW View_NHAP
AS
SELECT 
S.ID,
S.[NAME],
GD.CODE,
P.SOURCE_ID AS [FROM],
IIP.ITEM_ID,
SUM(IIP.QUANTITY) IMPORT
FROM dbo.PACKAGE P -- nhâp kho
LEFT JOIN dbo.[ITEM_IN_PACKAGE] IIP ON IIP.PACKAGE_ID = P.ID
LEFT JOIN base.[STEP] S ON S.ID = P.DESTINATION_ID
LEFT JOIN base.[GLOBAL_DATE] GD ON GD.YEAR = YEAR(P.CREATE_DATE) AND GD.MONTH = MONTH(P.CREATE_DATE) AND GD.DAY = DAY(P.CREATE_DATE)
WHERE P.VERIFY_BY IS NOT NULL
GROUP BY S.ID,
S.[NAME],
GD.CODE,
P.SOURCE_ID,
IIP.ITEM_ID
GO

CREATE OR ALTER VIEW View_XUAT_TRU_TON
AS
SELECT S.ID,
S.[NAME],
GD.CODE,
P.DESTINATION_ID AS [TO],
MIP.ITEM_ID,
SUM(MIP.QUANTITY) AS EXPORT
FROM dbo.[PACKAGE] P -- xuất hàng để trừ tồn kho 
LEFT JOIN dbo.[ITEM_IN_PACKAGE] IIP ON IIP.PACKAGE_ID = P.ID
LEFT JOIN dbo.[MATERIALS_IN_PACKAGE] MIP ON MIP.ITEM_IN_PACKAGE_ID = IIP.ID
LEFT JOIN base.[STEP] S ON S.ID = P.SOURCE_ID
LEFT JOIN base.[GLOBAL_DATE] GD ON GD.YEAR = YEAR(P.CREATE_DATE) AND GD.MONTH = MONTH(P.CREATE_DATE) AND GD.DAY = DAY(P.CREATE_DATE)
WHERE P.VERIFY_BY IS NOT NULL
GROUP BY S.ID,
S.[NAME],
GD.CODE,
P.DESTINATION_ID,
MIP.ITEM_ID
GO

CREATE OR ALTER VIEW View_XUAT
AS
SELECT S.ID,
S.[NAME],
GD.CODE,
P.DESTINATION_ID AS [TO],
IIP.ITEM_ID,
SUM(IIP.QUANTITY) EXPORT
FROM dbo.[PACKAGE] P -- xuất hàng thành phẩm kho 
LEFT JOIN dbo.[ITEM_IN_PACKAGE] IIP ON IIP.PACKAGE_ID = P.ID
LEFT JOIN base.[STEP] S ON S.ID = P.SOURCE_ID
LEFT JOIN base.[GLOBAL_DATE] GD ON GD.YEAR = YEAR(P.CREATE_DATE) AND GD.MONTH = MONTH(P.CREATE_DATE) AND GD.DAY = DAY(P.CREATE_DATE)
WHERE P.VERIFY_BY IS NOT NULL
GROUP BY S.ID,
S.[NAME],
GD.CODE,
P.DESTINATION_ID,
IIP.ITEM_ID

GO
CREATE OR ALTER VIEW View_NHAP_QC
AS
SELECT 
S.ID,
S.[NAME],
GD.CODE,
P.SOURCE_ID AS [FROM],
IIP.ITEM_ID,
SUM(IIP.QUANTITY) IMPORT
FROM dbo.PACKAGE P -- nhâp kho
LEFT JOIN dbo.[ITEM_IN_PACKAGE] IIP ON IIP.PACKAGE_ID = P.ID
LEFT JOIN base.[STEP] S ON S.ID = P.DESTINATION_ID
LEFT JOIN base.[GLOBAL_DATE] GD ON GD.YEAR = YEAR(P.CREATE_DATE) AND GD.MONTH = MONTH(P.CREATE_DATE) AND GD.DAY = DAY(P.CREATE_DATE)
--WHERE P.VERIFY_BY IS NOT NULL
GROUP BY S.ID,
S.[NAME],
GD.CODE,
P.SOURCE_ID,
IIP.ITEM_ID
GO
CREATE OR ALTER VIEW View_XUAT_QC
AS
SELECT S.ID,
S.[NAME],
GD.CODE,
P.DESTINATION_ID AS [TO],
P.ITEM_FROM_ID,
IIP.ITEM_ID,
SUM(IIP.QUANTITY) EXPORT
FROM dbo.[PACKAGE] P -- xuất hàng thành phẩm kho 
LEFT JOIN dbo.[ITEM_IN_PACKAGE] IIP ON IIP.PACKAGE_ID = P.ID
LEFT JOIN base.[STEP] S ON S.ID = P.SOURCE_ID
LEFT JOIN base.[GLOBAL_DATE] GD ON GD.YEAR = YEAR(P.CREATE_DATE) AND GD.MONTH = MONTH(P.CREATE_DATE) AND GD.DAY = DAY(P.CREATE_DATE)
--WHERE P.VERIFY_BY IS NOT NULL
GROUP BY S.ID,
S.[NAME],
GD.CODE,
P.DESTINATION_ID,
P.ITEM_FROM_ID,
IIP.ITEM_ID
GO

CREATE OR ALTER VIEW View_TON
AS
SELECT CASE
	WHEN N.ID IS NOT NULL THEN N.ID
	WHEN XTT.ID IS NOT NULL THEN XTT.ID
	ELSE X.ID
END STEP_ID,
CASE
	WHEN N.CODE IS NOT NULL THEN N.CODE
	WHEN XTT.CODE IS NOT NULL THEN XTT.CODE
	ELSE X.CODE
END CODE,
CASE
	WHEN N.ITEM_ID IS NOT NULL THEN N.ITEM_ID
	WHEN XTT.ITEM_ID IS NOT NULL THEN XTT.ITEM_ID
	ELSE X.ITEM_ID
END ITEM_ID,
N.IMPORT,
XTT.EXPORT EXPORT_NVL,
X.EXPORT,
CASE 
	WHEN N.IMPORT IS NULL THEN XTT.EXPORT * (-1)
	WHEN XTT.EXPORT IS NULL THEN N.IMPORT
	ELSE N.IMPORT - XTT.EXPORT
END REMAIN
FROM View_NHAP N
FULL JOIN View_XUAT_TRU_TON XTT ON XTT.ID = N.ID AND XTT.CODE = N.CODE AND XTT.ITEM_ID = N.ITEM_ID
FULL JOIN View_XUAT X ON X.ID = N.ID AND X.CODE = N.CODE AND X.ITEM_ID = N.ITEM_ID
WHERE N.ID IS NOT NULL 
OR XTT.ID IS NOT NULL

GO

CREATE OR ALTER VIEW View_TON_QC
AS
SELECT * 
FROM (
SELECT N.ID,N.[FROM],N.ITEM_ID, 
CASE 
WHEN N.IMPORT IS NULL AND X.EXPORT IS NULL THEN 0
WHEN N.IMPORT IS NULL AND X.EXPORT IS NOT NULL THEN X.EXPORT*(-1)
WHEN N.IMPORT IS NOT NULL AND X.EXPORT IS NULL THEN N.IMPORT
WHEN N.IMPORT IS NOT NULL AND X.EXPORT IS NOT NULL THEN N.IMPORT - X.EXPORT
ELSE N.IMPORT - X.EXPORT
END AS REMAIN
FROM
(
SELECT ID,[FROM],ITEM_ID,SUM(IMPORT) IMPORT
FROM View_NHAP_QC
--WHERE ID = 100025
GROUP BY ID,[FROM],ITEM_ID
) N LEFT JOIN
(
SELECT ID,ITEM_FROM_ID,ITEM_ID,SUM(EXPORT) EXPORT
FROM View_XUAT_QC
--WHERE ID = 100025
GROUP BY ID, ITEM_FROM_ID,ITEM_ID
) X ON N.ID = X.ID AND N.[FROM] = X.ITEM_FROM_ID AND N.ITEM_ID = X.ITEM_ID
) TON 
WHERE TON.REMAIN > 0
GO

SELECT * FROM View_NHAP
SELECT * FROM View_XUAT
SELECT * FROM View_XUAT_TRU_TON
SELECT * FROM View_TON

SELECT * FROM View_NHAP_QC
WHERE ID = 100025
SELECT * FROM View_XUAT_QC
WHERE ID = 100025
SELECT * FROM View_TON_QC
WHERE ID = 100025


SELECT * FROM dbo.PACKAGE WHERE ITEM_FROM_ID IS NOT NULL




