
CREATE OR ALTER VIEW View_raw_data
AS
SELECT P.ID
, GD.[YEAR] N'Năm'
, GD.[WEEK] N'Tuần'
, GD.[WEEK_DAY] N'Thứ'
, S.ID 'DEPARTMENT_ID'
, S.NAME N'Tổ'
, D.NAME N'Nơi xuất'
, PL.CODE N'Mã pallet'
, SOP.PASS N'Đạt'
, SOP.NOT_PASS N'Không đạt'
, I.[NAME] N'Chi tiết/cụm'
, U.[NAME] unit
, IIP.QUANTITY N'Số lượng'
, CB.LAST_NAME N'Người tạo'
, P.CREATE_DATE N'Ngày tạo' 
, VB.LAST_NAME N'Người nhận'
, P.VERIFY_DATE N'Ngày nhận'
FROM prod.PACKAGE P
LEFT JOIN base.DEPARTMENT S ON S.ID = P.SOURCE_ID
LEFT JOIN base.DEPARTMENT D ON D.ID = P.DESTINATION_ID
LEFT JOIN prod.STEP_OF_PALLET SOP ON SOP.ID = P.STEP_OF_PALLET_ID
LEFT JOIN prod.PALLET PL ON PL.ID = SOP.PALLET_ID
LEFT JOIN prod.ITEM_IN_PACKAGE IIP ON IIP.PACKAGE_ID = P.ID
LEFT JOIN base.ITEM I ON I.ID = IIP.ITEM_ID
LEFT JOIN base.UNIT U ON U.ID = I.UNIT_ID
LEFT JOIN base.ACCOUNT CB ON CB.ID = P.CREATE_BY
LEFT JOIN base.ACCOUNT VB ON VB.ID = P.VERIFY_BY
LEFT JOIN base.GLOBAL_DATE GD ON GD.[DATE] =  CAST(P.CREATE_DATE AS DATE) 