CREATE   VIEW [prod].[View_not_out_item]
AS
SELECT PL.ID,
IIP.ITEM_ID,
IIP.QUANTITY,
SOP.STEP_NEXT_ID
FROM prod.[STEP_OF_PALLET] SOP
LEFT JOIN prod.[PACKAGE] P ON P.STEP_OF_PALLET_ID = SOP.ID AND P.DESTINATION_ID = SOP.STEP_NEXT_ID
LEFT JOIN prod.[PALLET] PL ON PL.ID = SOP.PALLET_ID
LEFT JOIN prod.[STEP_OF_PALLET] SOPOUT ON SOPOUT.PALLET_ID = SOP.PALLET_ID AND SOPOUT.STEP_ID = SOP.STEP_NEXT_ID
LEFT JOIN prod.[ITEM_IN_PALLET] IIP ON IIP.PALLET_ID = PL.ID
WHERE P.VERIFY_BY IS NOT NULL -- đã nhận
AND SOPOUT.ID IS NULL -- nhưng chưa xuất