CREATE OR ALTER  VIEW [prod].[View_not_out]
AS
SELECT 
SOP.STEP_ID,
SOP.STEP_NEXT_ID,
SOP.ITEM_ID,
SOP.PASS,
PL.ID PALLET_ID,
PL.CODE PALLET_CODE,
PL.TYPE_ID PALLET_TYPE_ID,
P.ID PACKAGE_ID,
P.CREATE_BY,
P.CREATE_DATE,
P.VERIFY_BY,
P.VERIFY_DATE
FROM prod.[STEP_OF_PALLET] SOP
LEFT JOIN prod.[PACKAGE] P ON P.STEP_OF_PALLET_ID = SOP.ID AND P.DESTINATION_ID = SOP.STEP_NEXT_ID
LEFT JOIN prod.[PALLET] PL ON PL.ID = SOP.PALLET_ID
LEFT JOIN prod.[STEP_OF_PALLET] SOPOUT ON SOPOUT.PALLET_ID = SOP.PALLET_ID AND SOPOUT.STEP_ID = SOP.STEP_NEXT_ID
WHERE P.VERIFY_BY IS NOT NULL -- đã nhận
AND SOPOUT.ID IS NULL -- nhưng chưa xuất