
-- SELECT * FROM View_getPalletCreated
-- ORDER BY ID DESC
CREATE OR ALTER VIEW View_getPalletCreated
AS
SELECT PLS.ID,PLS.CODE,PLS.CREATE_BY,PLS.CREATE_DATE,PLS.STEP_ID,PLS.STEP_NEXT_ID,P.VERIFY_BY,P.VERIFY_DATE
FROM (
SELECT PL.ID,PL.CODE,PL.CREATE_BY,PL.CREATE_DATE,SOP.ID STEP_OF_PALLET_ID,SOP.STEP_ID,SOP.STEP_NEXT_ID,ROW_NUMBER() OVER(PARTITION BY PL.ID ORDER BY SOP.ID ASC) AS STEP_RANK
FROM prod.[STEP_OF_PALLET] SOP
LEFT JOIN prod.[PALLET] PL ON PL.ID = SOP.PALLET_ID
) PLS
LEFT JOIN prod.[PACKAGE] P ON P.STEP_OF_PALLET_ID = PLS.STEP_OF_PALLET_ID
WHERE PLS.STEP_RANK = 1

