
-- SELECT * FROM View_getPalletStep
CREATE OR ALTER VIEW View_getPalletStep
AS
SELECT PLS.ID,PLS.CODE,PLS.CREATE_BY,PLS.CREATE_DATE,P.ID PACKAGE_ID,P.SOURCE_ID,P.DESTINATION_ID,P.VERIFY_BY,P.VERIFY_DATE,PLS.STEP_RANK
FROM (
SELECT PL.ID,PL.CODE,PL.CREATE_BY,PL.CREATE_DATE,SOP.ID STEP_OF_PALLET_ID,SOP.STEP_ID,SOP.STEP_NEXT_ID,ROW_NUMBER() OVER(PARTITION BY PL.ID ORDER BY SOP.ID ASC) AS STEP_RANK
FROM prod.[STEP_OF_PALLET] SOP
LEFT JOIN prod.[PALLET] PL ON PL.ID = SOP.PALLET_ID
) PLS
LEFT JOIN prod.[PACKAGE] P ON P.STEP_OF_PALLET_ID = PLS.STEP_OF_PALLET_ID


